#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdriaTicket.com.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="prstacpr_bk_testna")]
	public partial class AdriaTicketDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSEC_LK_Korisnik(SEC_LK_Korisnik instance);
    partial void UpdateSEC_LK_Korisnik(SEC_LK_Korisnik instance);
    partial void DeleteSEC_LK_Korisnik(SEC_LK_Korisnik instance);
    partial void InsertLK_Event(LK_Event instance);
    partial void UpdateLK_Event(LK_Event instance);
    partial void DeleteLK_Event(LK_Event instance);
    partial void InsertLK_StatusEventa(LK_StatusEventa instance);
    partial void UpdateLK_StatusEventa(LK_StatusEventa instance);
    partial void DeleteLK_StatusEventa(LK_StatusEventa instance);
    partial void InsertREL_EventLayoutSektor(REL_EventLayoutSektor instance);
    partial void UpdateREL_EventLayoutSektor(REL_EventLayoutSektor instance);
    partial void DeleteREL_EventLayoutSektor(REL_EventLayoutSektor instance);
    partial void InsertLK_Organizator(LK_Organizator instance);
    partial void UpdateLK_Organizator(LK_Organizator instance);
    partial void DeleteLK_Organizator(LK_Organizator instance);
    partial void InsertLK_LayoutDvorana(LK_LayoutDvorana instance);
    partial void UpdateLK_LayoutDvorana(LK_LayoutDvorana instance);
    partial void DeleteLK_LayoutDvorana(LK_LayoutDvorana instance);
    partial void InsertLK_Dvorana(LK_Dvorana instance);
    partial void UpdateLK_Dvorana(LK_Dvorana instance);
    partial void DeleteLK_Dvorana(LK_Dvorana instance);
    partial void InsertLK_Mjesto(LK_Mjesto instance);
    partial void UpdateLK_Mjesto(LK_Mjesto instance);
    partial void DeleteLK_Mjesto(LK_Mjesto instance);
    partial void InsertLK_Drzava(LK_Drzava instance);
    partial void UpdateLK_Drzava(LK_Drzava instance);
    partial void DeleteLK_Drzava(LK_Drzava instance);
    partial void InsertBK_ImageGallery(BK_ImageGallery instance);
    partial void UpdateBK_ImageGallery(BK_ImageGallery instance);
    partial void DeleteBK_ImageGallery(BK_ImageGallery instance);
    partial void InsertBK_Image(BK_Image instance);
    partial void UpdateBK_Image(BK_Image instance);
    partial void DeleteBK_Image(BK_Image instance);
    partial void InsertBK_REL_Event_ImageGallery(BK_REL_Event_ImageGallery instance);
    partial void UpdateBK_REL_Event_ImageGallery(BK_REL_Event_ImageGallery instance);
    partial void DeleteBK_REL_Event_ImageGallery(BK_REL_Event_ImageGallery instance);
    #endregion
		
		public AdriaTicketDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["prstacpr_bk_testnaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SEC_LK_Korisnik> SEC_LK_Korisniks
		{
			get
			{
				return this.GetTable<SEC_LK_Korisnik>();
			}
		}
		
		public System.Data.Linq.Table<LK_Event> LK_Events
		{
			get
			{
				return this.GetTable<LK_Event>();
			}
		}
		
		public System.Data.Linq.Table<LK_StatusEventa> LK_StatusEventas
		{
			get
			{
				return this.GetTable<LK_StatusEventa>();
			}
		}
		
		public System.Data.Linq.Table<REL_EventLayoutSektor> REL_EventLayoutSektors
		{
			get
			{
				return this.GetTable<REL_EventLayoutSektor>();
			}
		}
		
		public System.Data.Linq.Table<LK_Organizator> LK_Organizators
		{
			get
			{
				return this.GetTable<LK_Organizator>();
			}
		}
		
		public System.Data.Linq.Table<LK_LayoutDvorana> LK_LayoutDvoranas
		{
			get
			{
				return this.GetTable<LK_LayoutDvorana>();
			}
		}
		
		public System.Data.Linq.Table<LK_Dvorana> LK_Dvoranas
		{
			get
			{
				return this.GetTable<LK_Dvorana>();
			}
		}
		
		public System.Data.Linq.Table<LK_Mjesto> LK_Mjestos
		{
			get
			{
				return this.GetTable<LK_Mjesto>();
			}
		}
		
		public System.Data.Linq.Table<LK_Drzava> LK_Drzavas
		{
			get
			{
				return this.GetTable<LK_Drzava>();
			}
		}
		
		public System.Data.Linq.Table<BK_ImageGallery> BK_ImageGalleries
		{
			get
			{
				return this.GetTable<BK_ImageGallery>();
			}
		}
		
		public System.Data.Linq.Table<BK_Image> BK_Images
		{
			get
			{
				return this.GetTable<BK_Image>();
			}
		}
		
		public System.Data.Linq.Table<BK_REL_Event_ImageGallery> BK_REL_Event_ImageGalleries
		{
			get
			{
				return this.GetTable<BK_REL_Event_ImageGallery>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SEC_LK_Korisnik")]
	public partial class SEC_LK_Korisnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KOR_Id;
		
		private int _KOR_IdDjelatnik;
		
		private string _KOR_Login;
		
		private string _KOR_Zaporka;
		
		private string _KOR_Napomena;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOR_IdChanging(int value);
    partial void OnKOR_IdChanged();
    partial void OnKOR_IdDjelatnikChanging(int value);
    partial void OnKOR_IdDjelatnikChanged();
    partial void OnKOR_LoginChanging(string value);
    partial void OnKOR_LoginChanged();
    partial void OnKOR_ZaporkaChanging(string value);
    partial void OnKOR_ZaporkaChanged();
    partial void OnKOR_NapomenaChanging(string value);
    partial void OnKOR_NapomenaChanged();
    #endregion
		
		public SEC_LK_Korisnik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KOR_Id
		{
			get
			{
				return this._KOR_Id;
			}
			set
			{
				if ((this._KOR_Id != value))
				{
					this.OnKOR_IdChanging(value);
					this.SendPropertyChanging();
					this._KOR_Id = value;
					this.SendPropertyChanged("KOR_Id");
					this.OnKOR_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_IdDjelatnik", DbType="Int NOT NULL")]
		public int KOR_IdDjelatnik
		{
			get
			{
				return this._KOR_IdDjelatnik;
			}
			set
			{
				if ((this._KOR_IdDjelatnik != value))
				{
					this.OnKOR_IdDjelatnikChanging(value);
					this.SendPropertyChanging();
					this._KOR_IdDjelatnik = value;
					this.SendPropertyChanged("KOR_IdDjelatnik");
					this.OnKOR_IdDjelatnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Login", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string KOR_Login
		{
			get
			{
				return this._KOR_Login;
			}
			set
			{
				if ((this._KOR_Login != value))
				{
					this.OnKOR_LoginChanging(value);
					this.SendPropertyChanging();
					this._KOR_Login = value;
					this.SendPropertyChanged("KOR_Login");
					this.OnKOR_LoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Zaporka", DbType="VarChar(MAX)")]
		public string KOR_Zaporka
		{
			get
			{
				return this._KOR_Zaporka;
			}
			set
			{
				if ((this._KOR_Zaporka != value))
				{
					this.OnKOR_ZaporkaChanging(value);
					this.SendPropertyChanging();
					this._KOR_Zaporka = value;
					this.SendPropertyChanged("KOR_Zaporka");
					this.OnKOR_ZaporkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Napomena", DbType="NVarChar(100)")]
		public string KOR_Napomena
		{
			get
			{
				return this._KOR_Napomena;
			}
			set
			{
				if ((this._KOR_Napomena != value))
				{
					this.OnKOR_NapomenaChanging(value);
					this.SendPropertyChanging();
					this._KOR_Napomena = value;
					this.SendPropertyChanged("KOR_Napomena");
					this.OnKOR_NapomenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_Event")]
	public partial class LK_Event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EVE_Id;
		
		private string _EVE_Naziv;
		
		private System.Nullable<System.DateTime> _EVE_Datum;
		
		private string _EVE_Opis;
		
		private System.Nullable<int> _EVE_MjestoId;
		
		private System.Nullable<int> _EVE_DvoranaId;
		
		private System.Nullable<int> _EVE_LayoutId;
		
		private int _EVE_StatusEventaId;
		
		private System.Nullable<bool> _EVE_PotrebanKupac;
		
		private System.DateTime _EVE_Timestamp;
		
		private char _EVE_Stanje;
		
		private System.Nullable<System.DateTime> _EVE_DatumOdPretprodaja;
		
		private System.Nullable<System.DateTime> _EVE_DatumOdProdaja;
		
		private decimal _EVE_PostotakProvizije;
		
		private int _EVE_OrganizatorId;
		
		private bool _EVE_PrikaziNaWebu;
		
		private string _EVE_ImagePath;
		
		private string _EVE_ImageSmallPath;
		
		private bool _EVE_ImageExist;
		
		private string _EVE_Napomena;
		
		private string _EVE_ReklamaPath;
		
		private bool _EVE_ReklamaExist;
		
		private System.Nullable<int> _EVE_BrojGlavnogEventa;
		
		private bool _EVE_FlagOnlineProdaja;
		
		private System.Nullable<int> _EVE_MaksimalniBrojKarata;
		
		private System.Nullable<decimal> _EVE_PDVIznos;
		
		private EntityRef<LK_StatusEventa> _LK_StatusEventa;
		
		private EntityRef<LK_Organizator> _LK_Organizator;
		
		private EntityRef<LK_LayoutDvorana> _LK_LayoutDvorana;
		
		private EntityRef<LK_Dvorana> _LK_Dvorana;
		
		private EntityRef<LK_Mjesto> _LK_Mjesto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEVE_IdChanging(int value);
    partial void OnEVE_IdChanged();
    partial void OnEVE_NazivChanging(string value);
    partial void OnEVE_NazivChanged();
    partial void OnEVE_DatumChanging(System.Nullable<System.DateTime> value);
    partial void OnEVE_DatumChanged();
    partial void OnEVE_OpisChanging(string value);
    partial void OnEVE_OpisChanged();
    partial void OnEVE_MjestoIdChanging(System.Nullable<int> value);
    partial void OnEVE_MjestoIdChanged();
    partial void OnEVE_DvoranaIdChanging(System.Nullable<int> value);
    partial void OnEVE_DvoranaIdChanged();
    partial void OnEVE_LayoutIdChanging(System.Nullable<int> value);
    partial void OnEVE_LayoutIdChanged();
    partial void OnEVE_StatusEventaIdChanging(int value);
    partial void OnEVE_StatusEventaIdChanged();
    partial void OnEVE_PotrebanKupacChanging(System.Nullable<bool> value);
    partial void OnEVE_PotrebanKupacChanged();
    partial void OnEVE_TimestampChanging(System.DateTime value);
    partial void OnEVE_TimestampChanged();
    partial void OnEVE_StanjeChanging(char value);
    partial void OnEVE_StanjeChanged();
    partial void OnEVE_DatumOdPretprodajaChanging(System.Nullable<System.DateTime> value);
    partial void OnEVE_DatumOdPretprodajaChanged();
    partial void OnEVE_DatumOdProdajaChanging(System.Nullable<System.DateTime> value);
    partial void OnEVE_DatumOdProdajaChanged();
    partial void OnEVE_PostotakProvizijeChanging(decimal value);
    partial void OnEVE_PostotakProvizijeChanged();
    partial void OnEVE_OrganizatorIdChanging(int value);
    partial void OnEVE_OrganizatorIdChanged();
    partial void OnEVE_PrikaziNaWebuChanging(bool value);
    partial void OnEVE_PrikaziNaWebuChanged();
    partial void OnEVE_ImagePathChanging(string value);
    partial void OnEVE_ImagePathChanged();
    partial void OnEVE_ImageSmallPathChanging(string value);
    partial void OnEVE_ImageSmallPathChanged();
    partial void OnEVE_ImageExistChanging(bool value);
    partial void OnEVE_ImageExistChanged();
    partial void OnEVE_NapomenaChanging(string value);
    partial void OnEVE_NapomenaChanged();
    partial void OnEVE_ReklamaPathChanging(string value);
    partial void OnEVE_ReklamaPathChanged();
    partial void OnEVE_ReklamaExistChanging(bool value);
    partial void OnEVE_ReklamaExistChanged();
    partial void OnEVE_BrojGlavnogEventaChanging(System.Nullable<int> value);
    partial void OnEVE_BrojGlavnogEventaChanged();
    partial void OnEVE_FlagOnlineProdajaChanging(bool value);
    partial void OnEVE_FlagOnlineProdajaChanged();
    partial void OnEVE_MaksimalniBrojKarataChanging(System.Nullable<int> value);
    partial void OnEVE_MaksimalniBrojKarataChanged();
    partial void OnEVE_PDVIznosChanging(System.Nullable<decimal> value);
    partial void OnEVE_PDVIznosChanged();
    #endregion
		
		public LK_Event()
		{
			this._LK_StatusEventa = default(EntityRef<LK_StatusEventa>);
			this._LK_Organizator = default(EntityRef<LK_Organizator>);
			this._LK_LayoutDvorana = default(EntityRef<LK_LayoutDvorana>);
			this._LK_Dvorana = default(EntityRef<LK_Dvorana>);
			this._LK_Mjesto = default(EntityRef<LK_Mjesto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EVE_Id
		{
			get
			{
				return this._EVE_Id;
			}
			set
			{
				if ((this._EVE_Id != value))
				{
					this.OnEVE_IdChanging(value);
					this.SendPropertyChanging();
					this._EVE_Id = value;
					this.SendPropertyChanged("EVE_Id");
					this.OnEVE_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EVE_Naziv
		{
			get
			{
				return this._EVE_Naziv;
			}
			set
			{
				if ((this._EVE_Naziv != value))
				{
					this.OnEVE_NazivChanging(value);
					this.SendPropertyChanging();
					this._EVE_Naziv = value;
					this.SendPropertyChanged("EVE_Naziv");
					this.OnEVE_NazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Datum", DbType="DateTime")]
		public System.Nullable<System.DateTime> EVE_Datum
		{
			get
			{
				return this._EVE_Datum;
			}
			set
			{
				if ((this._EVE_Datum != value))
				{
					this.OnEVE_DatumChanging(value);
					this.SendPropertyChanging();
					this._EVE_Datum = value;
					this.SendPropertyChanged("EVE_Datum");
					this.OnEVE_DatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Opis", DbType="NVarChar(MAX)")]
		public string EVE_Opis
		{
			get
			{
				return this._EVE_Opis;
			}
			set
			{
				if ((this._EVE_Opis != value))
				{
					this.OnEVE_OpisChanging(value);
					this.SendPropertyChanging();
					this._EVE_Opis = value;
					this.SendPropertyChanged("EVE_Opis");
					this.OnEVE_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_MjestoId", DbType="Int")]
		public System.Nullable<int> EVE_MjestoId
		{
			get
			{
				return this._EVE_MjestoId;
			}
			set
			{
				if ((this._EVE_MjestoId != value))
				{
					if (this._LK_Mjesto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEVE_MjestoIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_MjestoId = value;
					this.SendPropertyChanged("EVE_MjestoId");
					this.OnEVE_MjestoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_DvoranaId", DbType="Int")]
		public System.Nullable<int> EVE_DvoranaId
		{
			get
			{
				return this._EVE_DvoranaId;
			}
			set
			{
				if ((this._EVE_DvoranaId != value))
				{
					if (this._LK_Dvorana.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEVE_DvoranaIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_DvoranaId = value;
					this.SendPropertyChanged("EVE_DvoranaId");
					this.OnEVE_DvoranaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_LayoutId", DbType="Int")]
		public System.Nullable<int> EVE_LayoutId
		{
			get
			{
				return this._EVE_LayoutId;
			}
			set
			{
				if ((this._EVE_LayoutId != value))
				{
					if (this._LK_LayoutDvorana.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEVE_LayoutIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_LayoutId = value;
					this.SendPropertyChanged("EVE_LayoutId");
					this.OnEVE_LayoutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_StatusEventaId", DbType="Int NOT NULL")]
		public int EVE_StatusEventaId
		{
			get
			{
				return this._EVE_StatusEventaId;
			}
			set
			{
				if ((this._EVE_StatusEventaId != value))
				{
					if (this._LK_StatusEventa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEVE_StatusEventaIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_StatusEventaId = value;
					this.SendPropertyChanged("EVE_StatusEventaId");
					this.OnEVE_StatusEventaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PotrebanKupac", DbType="Bit")]
		public System.Nullable<bool> EVE_PotrebanKupac
		{
			get
			{
				return this._EVE_PotrebanKupac;
			}
			set
			{
				if ((this._EVE_PotrebanKupac != value))
				{
					this.OnEVE_PotrebanKupacChanging(value);
					this.SendPropertyChanging();
					this._EVE_PotrebanKupac = value;
					this.SendPropertyChanged("EVE_PotrebanKupac");
					this.OnEVE_PotrebanKupacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime EVE_Timestamp
		{
			get
			{
				return this._EVE_Timestamp;
			}
			set
			{
				if ((this._EVE_Timestamp != value))
				{
					this.OnEVE_TimestampChanging(value);
					this.SendPropertyChanging();
					this._EVE_Timestamp = value;
					this.SendPropertyChanged("EVE_Timestamp");
					this.OnEVE_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Stanje", DbType="Char(1) NOT NULL")]
		public char EVE_Stanje
		{
			get
			{
				return this._EVE_Stanje;
			}
			set
			{
				if ((this._EVE_Stanje != value))
				{
					this.OnEVE_StanjeChanging(value);
					this.SendPropertyChanging();
					this._EVE_Stanje = value;
					this.SendPropertyChanged("EVE_Stanje");
					this.OnEVE_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_DatumOdPretprodaja", DbType="DateTime")]
		public System.Nullable<System.DateTime> EVE_DatumOdPretprodaja
		{
			get
			{
				return this._EVE_DatumOdPretprodaja;
			}
			set
			{
				if ((this._EVE_DatumOdPretprodaja != value))
				{
					this.OnEVE_DatumOdPretprodajaChanging(value);
					this.SendPropertyChanging();
					this._EVE_DatumOdPretprodaja = value;
					this.SendPropertyChanged("EVE_DatumOdPretprodaja");
					this.OnEVE_DatumOdPretprodajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_DatumOdProdaja", DbType="DateTime")]
		public System.Nullable<System.DateTime> EVE_DatumOdProdaja
		{
			get
			{
				return this._EVE_DatumOdProdaja;
			}
			set
			{
				if ((this._EVE_DatumOdProdaja != value))
				{
					this.OnEVE_DatumOdProdajaChanging(value);
					this.SendPropertyChanging();
					this._EVE_DatumOdProdaja = value;
					this.SendPropertyChanged("EVE_DatumOdProdaja");
					this.OnEVE_DatumOdProdajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PostotakProvizije", DbType="Decimal(9,2) NOT NULL")]
		public decimal EVE_PostotakProvizije
		{
			get
			{
				return this._EVE_PostotakProvizije;
			}
			set
			{
				if ((this._EVE_PostotakProvizije != value))
				{
					this.OnEVE_PostotakProvizijeChanging(value);
					this.SendPropertyChanging();
					this._EVE_PostotakProvizije = value;
					this.SendPropertyChanged("EVE_PostotakProvizije");
					this.OnEVE_PostotakProvizijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_OrganizatorId", DbType="Int NOT NULL")]
		public int EVE_OrganizatorId
		{
			get
			{
				return this._EVE_OrganizatorId;
			}
			set
			{
				if ((this._EVE_OrganizatorId != value))
				{
					if (this._LK_Organizator.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEVE_OrganizatorIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_OrganizatorId = value;
					this.SendPropertyChanged("EVE_OrganizatorId");
					this.OnEVE_OrganizatorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PrikaziNaWebu", DbType="Bit NOT NULL")]
		public bool EVE_PrikaziNaWebu
		{
			get
			{
				return this._EVE_PrikaziNaWebu;
			}
			set
			{
				if ((this._EVE_PrikaziNaWebu != value))
				{
					this.OnEVE_PrikaziNaWebuChanging(value);
					this.SendPropertyChanging();
					this._EVE_PrikaziNaWebu = value;
					this.SendPropertyChanged("EVE_PrikaziNaWebu");
					this.OnEVE_PrikaziNaWebuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ImagePath", DbType="NVarChar(MAX)")]
		public string EVE_ImagePath
		{
			get
			{
				return this._EVE_ImagePath;
			}
			set
			{
				if ((this._EVE_ImagePath != value))
				{
					this.OnEVE_ImagePathChanging(value);
					this.SendPropertyChanging();
					this._EVE_ImagePath = value;
					this.SendPropertyChanged("EVE_ImagePath");
					this.OnEVE_ImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ImageSmallPath", DbType="NVarChar(MAX)")]
		public string EVE_ImageSmallPath
		{
			get
			{
				return this._EVE_ImageSmallPath;
			}
			set
			{
				if ((this._EVE_ImageSmallPath != value))
				{
					this.OnEVE_ImageSmallPathChanging(value);
					this.SendPropertyChanging();
					this._EVE_ImageSmallPath = value;
					this.SendPropertyChanged("EVE_ImageSmallPath");
					this.OnEVE_ImageSmallPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ImageExist", DbType="Bit NOT NULL")]
		public bool EVE_ImageExist
		{
			get
			{
				return this._EVE_ImageExist;
			}
			set
			{
				if ((this._EVE_ImageExist != value))
				{
					this.OnEVE_ImageExistChanging(value);
					this.SendPropertyChanging();
					this._EVE_ImageExist = value;
					this.SendPropertyChanged("EVE_ImageExist");
					this.OnEVE_ImageExistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Napomena", DbType="NVarChar(MAX)")]
		public string EVE_Napomena
		{
			get
			{
				return this._EVE_Napomena;
			}
			set
			{
				if ((this._EVE_Napomena != value))
				{
					this.OnEVE_NapomenaChanging(value);
					this.SendPropertyChanging();
					this._EVE_Napomena = value;
					this.SendPropertyChanged("EVE_Napomena");
					this.OnEVE_NapomenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ReklamaPath", DbType="NVarChar(MAX)")]
		public string EVE_ReklamaPath
		{
			get
			{
				return this._EVE_ReklamaPath;
			}
			set
			{
				if ((this._EVE_ReklamaPath != value))
				{
					this.OnEVE_ReklamaPathChanging(value);
					this.SendPropertyChanging();
					this._EVE_ReklamaPath = value;
					this.SendPropertyChanged("EVE_ReklamaPath");
					this.OnEVE_ReklamaPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ReklamaExist", DbType="Bit NOT NULL")]
		public bool EVE_ReklamaExist
		{
			get
			{
				return this._EVE_ReklamaExist;
			}
			set
			{
				if ((this._EVE_ReklamaExist != value))
				{
					this.OnEVE_ReklamaExistChanging(value);
					this.SendPropertyChanging();
					this._EVE_ReklamaExist = value;
					this.SendPropertyChanged("EVE_ReklamaExist");
					this.OnEVE_ReklamaExistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_BrojGlavnogEventa", DbType="Int")]
		public System.Nullable<int> EVE_BrojGlavnogEventa
		{
			get
			{
				return this._EVE_BrojGlavnogEventa;
			}
			set
			{
				if ((this._EVE_BrojGlavnogEventa != value))
				{
					this.OnEVE_BrojGlavnogEventaChanging(value);
					this.SendPropertyChanging();
					this._EVE_BrojGlavnogEventa = value;
					this.SendPropertyChanged("EVE_BrojGlavnogEventa");
					this.OnEVE_BrojGlavnogEventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_FlagOnlineProdaja", DbType="Bit NOT NULL")]
		public bool EVE_FlagOnlineProdaja
		{
			get
			{
				return this._EVE_FlagOnlineProdaja;
			}
			set
			{
				if ((this._EVE_FlagOnlineProdaja != value))
				{
					this.OnEVE_FlagOnlineProdajaChanging(value);
					this.SendPropertyChanging();
					this._EVE_FlagOnlineProdaja = value;
					this.SendPropertyChanged("EVE_FlagOnlineProdaja");
					this.OnEVE_FlagOnlineProdajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_MaksimalniBrojKarata", DbType="Int")]
		public System.Nullable<int> EVE_MaksimalniBrojKarata
		{
			get
			{
				return this._EVE_MaksimalniBrojKarata;
			}
			set
			{
				if ((this._EVE_MaksimalniBrojKarata != value))
				{
					this.OnEVE_MaksimalniBrojKarataChanging(value);
					this.SendPropertyChanging();
					this._EVE_MaksimalniBrojKarata = value;
					this.SendPropertyChanged("EVE_MaksimalniBrojKarata");
					this.OnEVE_MaksimalniBrojKarataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PDVIznos", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> EVE_PDVIznos
		{
			get
			{
				return this._EVE_PDVIznos;
			}
			set
			{
				if ((this._EVE_PDVIznos != value))
				{
					this.OnEVE_PDVIznosChanging(value);
					this.SendPropertyChanging();
					this._EVE_PDVIznos = value;
					this.SendPropertyChanged("EVE_PDVIznos");
					this.OnEVE_PDVIznosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_StatusEventa_LK_Event", Storage="_LK_StatusEventa", ThisKey="EVE_StatusEventaId", OtherKey="SEV_Id", IsForeignKey=true)]
		public LK_StatusEventa LK_StatusEventa
		{
			get
			{
				return this._LK_StatusEventa.Entity;
			}
			set
			{
				LK_StatusEventa previousValue = this._LK_StatusEventa.Entity;
				if (((previousValue != value) 
							|| (this._LK_StatusEventa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_StatusEventa.Entity = null;
						previousValue.LK_Events.Remove(this);
					}
					this._LK_StatusEventa.Entity = value;
					if ((value != null))
					{
						value.LK_Events.Add(this);
						this._EVE_StatusEventaId = value.SEV_Id;
					}
					else
					{
						this._EVE_StatusEventaId = default(int);
					}
					this.SendPropertyChanged("LK_StatusEventa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Organizator_LK_Event", Storage="_LK_Organizator", ThisKey="EVE_OrganizatorId", OtherKey="ORG_Id", IsForeignKey=true)]
		public LK_Organizator LK_Organizator
		{
			get
			{
				return this._LK_Organizator.Entity;
			}
			set
			{
				LK_Organizator previousValue = this._LK_Organizator.Entity;
				if (((previousValue != value) 
							|| (this._LK_Organizator.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Organizator.Entity = null;
						previousValue.LK_Events.Remove(this);
					}
					this._LK_Organizator.Entity = value;
					if ((value != null))
					{
						value.LK_Events.Add(this);
						this._EVE_OrganizatorId = value.ORG_Id;
					}
					else
					{
						this._EVE_OrganizatorId = default(int);
					}
					this.SendPropertyChanged("LK_Organizator");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_LayoutDvorana_LK_Event", Storage="_LK_LayoutDvorana", ThisKey="EVE_LayoutId", OtherKey="LDV_Id", IsForeignKey=true)]
		public LK_LayoutDvorana LK_LayoutDvorana
		{
			get
			{
				return this._LK_LayoutDvorana.Entity;
			}
			set
			{
				LK_LayoutDvorana previousValue = this._LK_LayoutDvorana.Entity;
				if (((previousValue != value) 
							|| (this._LK_LayoutDvorana.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_LayoutDvorana.Entity = null;
						previousValue.LK_Events.Remove(this);
					}
					this._LK_LayoutDvorana.Entity = value;
					if ((value != null))
					{
						value.LK_Events.Add(this);
						this._EVE_LayoutId = value.LDV_Id;
					}
					else
					{
						this._EVE_LayoutId = default(Nullable<int>);
					}
					this.SendPropertyChanged("LK_LayoutDvorana");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Dvorana_LK_Event", Storage="_LK_Dvorana", ThisKey="EVE_DvoranaId", OtherKey="DVO_Id", IsForeignKey=true)]
		public LK_Dvorana LK_Dvorana
		{
			get
			{
				return this._LK_Dvorana.Entity;
			}
			set
			{
				LK_Dvorana previousValue = this._LK_Dvorana.Entity;
				if (((previousValue != value) 
							|| (this._LK_Dvorana.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Dvorana.Entity = null;
						previousValue.LK_Events.Remove(this);
					}
					this._LK_Dvorana.Entity = value;
					if ((value != null))
					{
						value.LK_Events.Add(this);
						this._EVE_DvoranaId = value.DVO_Id;
					}
					else
					{
						this._EVE_DvoranaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("LK_Dvorana");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Mjesto_LK_Event", Storage="_LK_Mjesto", ThisKey="EVE_MjestoId", OtherKey="MJE_Id", IsForeignKey=true)]
		public LK_Mjesto LK_Mjesto
		{
			get
			{
				return this._LK_Mjesto.Entity;
			}
			set
			{
				LK_Mjesto previousValue = this._LK_Mjesto.Entity;
				if (((previousValue != value) 
							|| (this._LK_Mjesto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Mjesto.Entity = null;
						previousValue.LK_Events.Remove(this);
					}
					this._LK_Mjesto.Entity = value;
					if ((value != null))
					{
						value.LK_Events.Add(this);
						this._EVE_MjestoId = value.MJE_Id;
					}
					else
					{
						this._EVE_MjestoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("LK_Mjesto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_StatusEventa")]
	public partial class LK_StatusEventa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SEV_Id;
		
		private string _SEV_Naziv;
		
		private string _SEV_SkraceniNaziv;
		
		private System.DateTime _SEV_Timestamp;
		
		private char _SEV_Stanje;
		
		private EntitySet<LK_Event> _LK_Events;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSEV_IdChanging(int value);
    partial void OnSEV_IdChanged();
    partial void OnSEV_NazivChanging(string value);
    partial void OnSEV_NazivChanged();
    partial void OnSEV_SkraceniNazivChanging(string value);
    partial void OnSEV_SkraceniNazivChanged();
    partial void OnSEV_TimestampChanging(System.DateTime value);
    partial void OnSEV_TimestampChanged();
    partial void OnSEV_StanjeChanging(char value);
    partial void OnSEV_StanjeChanged();
    #endregion
		
		public LK_StatusEventa()
		{
			this._LK_Events = new EntitySet<LK_Event>(new Action<LK_Event>(this.attach_LK_Events), new Action<LK_Event>(this.detach_LK_Events));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEV_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SEV_Id
		{
			get
			{
				return this._SEV_Id;
			}
			set
			{
				if ((this._SEV_Id != value))
				{
					this.OnSEV_IdChanging(value);
					this.SendPropertyChanging();
					this._SEV_Id = value;
					this.SendPropertyChanged("SEV_Id");
					this.OnSEV_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEV_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SEV_Naziv
		{
			get
			{
				return this._SEV_Naziv;
			}
			set
			{
				if ((this._SEV_Naziv != value))
				{
					this.OnSEV_NazivChanging(value);
					this.SendPropertyChanging();
					this._SEV_Naziv = value;
					this.SendPropertyChanged("SEV_Naziv");
					this.OnSEV_NazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEV_SkraceniNaziv", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string SEV_SkraceniNaziv
		{
			get
			{
				return this._SEV_SkraceniNaziv;
			}
			set
			{
				if ((this._SEV_SkraceniNaziv != value))
				{
					this.OnSEV_SkraceniNazivChanging(value);
					this.SendPropertyChanging();
					this._SEV_SkraceniNaziv = value;
					this.SendPropertyChanged("SEV_SkraceniNaziv");
					this.OnSEV_SkraceniNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEV_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime SEV_Timestamp
		{
			get
			{
				return this._SEV_Timestamp;
			}
			set
			{
				if ((this._SEV_Timestamp != value))
				{
					this.OnSEV_TimestampChanging(value);
					this.SendPropertyChanging();
					this._SEV_Timestamp = value;
					this.SendPropertyChanged("SEV_Timestamp");
					this.OnSEV_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEV_Stanje", DbType="Char(1) NOT NULL")]
		public char SEV_Stanje
		{
			get
			{
				return this._SEV_Stanje;
			}
			set
			{
				if ((this._SEV_Stanje != value))
				{
					this.OnSEV_StanjeChanging(value);
					this.SendPropertyChanging();
					this._SEV_Stanje = value;
					this.SendPropertyChanged("SEV_Stanje");
					this.OnSEV_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_StatusEventa_LK_Event", Storage="_LK_Events", ThisKey="SEV_Id", OtherKey="EVE_StatusEventaId")]
		public EntitySet<LK_Event> LK_Events
		{
			get
			{
				return this._LK_Events;
			}
			set
			{
				this._LK_Events.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_StatusEventa = this;
		}
		
		private void detach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_StatusEventa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REL_EventLayoutSektor")]
	public partial class REL_EventLayoutSektor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ELS_Id;
		
		private int _ELS_EventId;
		
		private int _ELS_LayoutDvoranaId;
		
		private int _ELS_SektorId;
		
		private bool _ELS_DopustiStorniranje;
		
		private string _ELS_Ulaz;
		
		private System.Nullable<int> _ELS_KapacitetSektora;
		
		private System.Nullable<int> _ELS_GrupaSektoraId;
		
		private System.Nullable<int> _ELS_Rezervirano;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnELS_IdChanging(int value);
    partial void OnELS_IdChanged();
    partial void OnELS_EventIdChanging(int value);
    partial void OnELS_EventIdChanged();
    partial void OnELS_LayoutDvoranaIdChanging(int value);
    partial void OnELS_LayoutDvoranaIdChanged();
    partial void OnELS_SektorIdChanging(int value);
    partial void OnELS_SektorIdChanged();
    partial void OnELS_DopustiStorniranjeChanging(bool value);
    partial void OnELS_DopustiStorniranjeChanged();
    partial void OnELS_UlazChanging(string value);
    partial void OnELS_UlazChanged();
    partial void OnELS_KapacitetSektoraChanging(System.Nullable<int> value);
    partial void OnELS_KapacitetSektoraChanged();
    partial void OnELS_GrupaSektoraIdChanging(System.Nullable<int> value);
    partial void OnELS_GrupaSektoraIdChanged();
    partial void OnELS_RezerviranoChanging(System.Nullable<int> value);
    partial void OnELS_RezerviranoChanged();
    #endregion
		
		public REL_EventLayoutSektor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ELS_Id
		{
			get
			{
				return this._ELS_Id;
			}
			set
			{
				if ((this._ELS_Id != value))
				{
					this.OnELS_IdChanging(value);
					this.SendPropertyChanging();
					this._ELS_Id = value;
					this.SendPropertyChanged("ELS_Id");
					this.OnELS_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_EventId", DbType="Int NOT NULL")]
		public int ELS_EventId
		{
			get
			{
				return this._ELS_EventId;
			}
			set
			{
				if ((this._ELS_EventId != value))
				{
					this.OnELS_EventIdChanging(value);
					this.SendPropertyChanging();
					this._ELS_EventId = value;
					this.SendPropertyChanged("ELS_EventId");
					this.OnELS_EventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_LayoutDvoranaId", DbType="Int NOT NULL")]
		public int ELS_LayoutDvoranaId
		{
			get
			{
				return this._ELS_LayoutDvoranaId;
			}
			set
			{
				if ((this._ELS_LayoutDvoranaId != value))
				{
					this.OnELS_LayoutDvoranaIdChanging(value);
					this.SendPropertyChanging();
					this._ELS_LayoutDvoranaId = value;
					this.SendPropertyChanged("ELS_LayoutDvoranaId");
					this.OnELS_LayoutDvoranaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_SektorId", DbType="Int NOT NULL")]
		public int ELS_SektorId
		{
			get
			{
				return this._ELS_SektorId;
			}
			set
			{
				if ((this._ELS_SektorId != value))
				{
					this.OnELS_SektorIdChanging(value);
					this.SendPropertyChanging();
					this._ELS_SektorId = value;
					this.SendPropertyChanged("ELS_SektorId");
					this.OnELS_SektorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_DopustiStorniranje", DbType="Bit NOT NULL")]
		public bool ELS_DopustiStorniranje
		{
			get
			{
				return this._ELS_DopustiStorniranje;
			}
			set
			{
				if ((this._ELS_DopustiStorniranje != value))
				{
					this.OnELS_DopustiStorniranjeChanging(value);
					this.SendPropertyChanging();
					this._ELS_DopustiStorniranje = value;
					this.SendPropertyChanged("ELS_DopustiStorniranje");
					this.OnELS_DopustiStorniranjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_Ulaz", DbType="NVarChar(50)")]
		public string ELS_Ulaz
		{
			get
			{
				return this._ELS_Ulaz;
			}
			set
			{
				if ((this._ELS_Ulaz != value))
				{
					this.OnELS_UlazChanging(value);
					this.SendPropertyChanging();
					this._ELS_Ulaz = value;
					this.SendPropertyChanged("ELS_Ulaz");
					this.OnELS_UlazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_KapacitetSektora", DbType="Int")]
		public System.Nullable<int> ELS_KapacitetSektora
		{
			get
			{
				return this._ELS_KapacitetSektora;
			}
			set
			{
				if ((this._ELS_KapacitetSektora != value))
				{
					this.OnELS_KapacitetSektoraChanging(value);
					this.SendPropertyChanging();
					this._ELS_KapacitetSektora = value;
					this.SendPropertyChanged("ELS_KapacitetSektora");
					this.OnELS_KapacitetSektoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_GrupaSektoraId", DbType="Int")]
		public System.Nullable<int> ELS_GrupaSektoraId
		{
			get
			{
				return this._ELS_GrupaSektoraId;
			}
			set
			{
				if ((this._ELS_GrupaSektoraId != value))
				{
					this.OnELS_GrupaSektoraIdChanging(value);
					this.SendPropertyChanging();
					this._ELS_GrupaSektoraId = value;
					this.SendPropertyChanged("ELS_GrupaSektoraId");
					this.OnELS_GrupaSektoraIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELS_Rezervirano", DbType="Int")]
		public System.Nullable<int> ELS_Rezervirano
		{
			get
			{
				return this._ELS_Rezervirano;
			}
			set
			{
				if ((this._ELS_Rezervirano != value))
				{
					this.OnELS_RezerviranoChanging(value);
					this.SendPropertyChanging();
					this._ELS_Rezervirano = value;
					this.SendPropertyChanged("ELS_Rezervirano");
					this.OnELS_RezerviranoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_Organizator")]
	public partial class LK_Organizator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ORG_Id;
		
		private string _ORG_Naziv;
		
		private string _ORG_Adresa;
		
		private string _ORG_OIB;
		
		private bool _ORG_FlagPDV;
		
		private System.DateTime _ORG_Timestamp;
		
		private char _ORG_Stanje;
		
		private EntitySet<LK_Event> _LK_Events;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnORG_IdChanging(int value);
    partial void OnORG_IdChanged();
    partial void OnORG_NazivChanging(string value);
    partial void OnORG_NazivChanged();
    partial void OnORG_AdresaChanging(string value);
    partial void OnORG_AdresaChanged();
    partial void OnORG_OIBChanging(string value);
    partial void OnORG_OIBChanged();
    partial void OnORG_FlagPDVChanging(bool value);
    partial void OnORG_FlagPDVChanged();
    partial void OnORG_TimestampChanging(System.DateTime value);
    partial void OnORG_TimestampChanged();
    partial void OnORG_StanjeChanging(char value);
    partial void OnORG_StanjeChanged();
    #endregion
		
		public LK_Organizator()
		{
			this._LK_Events = new EntitySet<LK_Event>(new Action<LK_Event>(this.attach_LK_Events), new Action<LK_Event>(this.detach_LK_Events));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ORG_Id
		{
			get
			{
				return this._ORG_Id;
			}
			set
			{
				if ((this._ORG_Id != value))
				{
					this.OnORG_IdChanging(value);
					this.SendPropertyChanging();
					this._ORG_Id = value;
					this.SendPropertyChanged("ORG_Id");
					this.OnORG_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ORG_Naziv
		{
			get
			{
				return this._ORG_Naziv;
			}
			set
			{
				if ((this._ORG_Naziv != value))
				{
					this.OnORG_NazivChanging(value);
					this.SendPropertyChanging();
					this._ORG_Naziv = value;
					this.SendPropertyChanged("ORG_Naziv");
					this.OnORG_NazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_Adresa", DbType="NVarChar(50)")]
		public string ORG_Adresa
		{
			get
			{
				return this._ORG_Adresa;
			}
			set
			{
				if ((this._ORG_Adresa != value))
				{
					this.OnORG_AdresaChanging(value);
					this.SendPropertyChanging();
					this._ORG_Adresa = value;
					this.SendPropertyChanged("ORG_Adresa");
					this.OnORG_AdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_OIB", DbType="NVarChar(20)")]
		public string ORG_OIB
		{
			get
			{
				return this._ORG_OIB;
			}
			set
			{
				if ((this._ORG_OIB != value))
				{
					this.OnORG_OIBChanging(value);
					this.SendPropertyChanging();
					this._ORG_OIB = value;
					this.SendPropertyChanged("ORG_OIB");
					this.OnORG_OIBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_FlagPDV", DbType="Bit NOT NULL")]
		public bool ORG_FlagPDV
		{
			get
			{
				return this._ORG_FlagPDV;
			}
			set
			{
				if ((this._ORG_FlagPDV != value))
				{
					this.OnORG_FlagPDVChanging(value);
					this.SendPropertyChanging();
					this._ORG_FlagPDV = value;
					this.SendPropertyChanged("ORG_FlagPDV");
					this.OnORG_FlagPDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime ORG_Timestamp
		{
			get
			{
				return this._ORG_Timestamp;
			}
			set
			{
				if ((this._ORG_Timestamp != value))
				{
					this.OnORG_TimestampChanging(value);
					this.SendPropertyChanging();
					this._ORG_Timestamp = value;
					this.SendPropertyChanged("ORG_Timestamp");
					this.OnORG_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORG_Stanje", DbType="Char(1) NOT NULL")]
		public char ORG_Stanje
		{
			get
			{
				return this._ORG_Stanje;
			}
			set
			{
				if ((this._ORG_Stanje != value))
				{
					this.OnORG_StanjeChanging(value);
					this.SendPropertyChanging();
					this._ORG_Stanje = value;
					this.SendPropertyChanged("ORG_Stanje");
					this.OnORG_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Organizator_LK_Event", Storage="_LK_Events", ThisKey="ORG_Id", OtherKey="EVE_OrganizatorId")]
		public EntitySet<LK_Event> LK_Events
		{
			get
			{
				return this._LK_Events;
			}
			set
			{
				this._LK_Events.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_Organizator = this;
		}
		
		private void detach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_Organizator = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_LayoutDvorana")]
	public partial class LK_LayoutDvorana : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LDV_Id;
		
		private string _LDV_Opis;
		
		private int _LDV_DvoranaId;
		
		private int _LDV_KapacitetSjedenje;
		
		private int _LDV_KapacitetStajanje;
		
		private System.DateTime _LDV_Timestamp;
		
		private char _LDV_Stanje;
		
		private EntitySet<LK_Event> _LK_Events;
		
		private EntityRef<LK_Dvorana> _LK_Dvorana;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLDV_IdChanging(int value);
    partial void OnLDV_IdChanged();
    partial void OnLDV_OpisChanging(string value);
    partial void OnLDV_OpisChanged();
    partial void OnLDV_DvoranaIdChanging(int value);
    partial void OnLDV_DvoranaIdChanged();
    partial void OnLDV_KapacitetSjedenjeChanging(int value);
    partial void OnLDV_KapacitetSjedenjeChanged();
    partial void OnLDV_KapacitetStajanjeChanging(int value);
    partial void OnLDV_KapacitetStajanjeChanged();
    partial void OnLDV_TimestampChanging(System.DateTime value);
    partial void OnLDV_TimestampChanged();
    partial void OnLDV_StanjeChanging(char value);
    partial void OnLDV_StanjeChanged();
    #endregion
		
		public LK_LayoutDvorana()
		{
			this._LK_Events = new EntitySet<LK_Event>(new Action<LK_Event>(this.attach_LK_Events), new Action<LK_Event>(this.detach_LK_Events));
			this._LK_Dvorana = default(EntityRef<LK_Dvorana>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDV_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LDV_Id
		{
			get
			{
				return this._LDV_Id;
			}
			set
			{
				if ((this._LDV_Id != value))
				{
					this.OnLDV_IdChanging(value);
					this.SendPropertyChanging();
					this._LDV_Id = value;
					this.SendPropertyChanged("LDV_Id");
					this.OnLDV_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDV_Opis", DbType="NVarChar(MAX)")]
		public string LDV_Opis
		{
			get
			{
				return this._LDV_Opis;
			}
			set
			{
				if ((this._LDV_Opis != value))
				{
					this.OnLDV_OpisChanging(value);
					this.SendPropertyChanging();
					this._LDV_Opis = value;
					this.SendPropertyChanged("LDV_Opis");
					this.OnLDV_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDV_DvoranaId", DbType="Int NOT NULL")]
		public int LDV_DvoranaId
		{
			get
			{
				return this._LDV_DvoranaId;
			}
			set
			{
				if ((this._LDV_DvoranaId != value))
				{
					if (this._LK_Dvorana.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLDV_DvoranaIdChanging(value);
					this.SendPropertyChanging();
					this._LDV_DvoranaId = value;
					this.SendPropertyChanged("LDV_DvoranaId");
					this.OnLDV_DvoranaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDV_KapacitetSjedenje", DbType="Int NOT NULL")]
		public int LDV_KapacitetSjedenje
		{
			get
			{
				return this._LDV_KapacitetSjedenje;
			}
			set
			{
				if ((this._LDV_KapacitetSjedenje != value))
				{
					this.OnLDV_KapacitetSjedenjeChanging(value);
					this.SendPropertyChanging();
					this._LDV_KapacitetSjedenje = value;
					this.SendPropertyChanged("LDV_KapacitetSjedenje");
					this.OnLDV_KapacitetSjedenjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDV_KapacitetStajanje", DbType="Int NOT NULL")]
		public int LDV_KapacitetStajanje
		{
			get
			{
				return this._LDV_KapacitetStajanje;
			}
			set
			{
				if ((this._LDV_KapacitetStajanje != value))
				{
					this.OnLDV_KapacitetStajanjeChanging(value);
					this.SendPropertyChanging();
					this._LDV_KapacitetStajanje = value;
					this.SendPropertyChanged("LDV_KapacitetStajanje");
					this.OnLDV_KapacitetStajanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDV_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime LDV_Timestamp
		{
			get
			{
				return this._LDV_Timestamp;
			}
			set
			{
				if ((this._LDV_Timestamp != value))
				{
					this.OnLDV_TimestampChanging(value);
					this.SendPropertyChanging();
					this._LDV_Timestamp = value;
					this.SendPropertyChanged("LDV_Timestamp");
					this.OnLDV_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LDV_Stanje", DbType="Char(1) NOT NULL")]
		public char LDV_Stanje
		{
			get
			{
				return this._LDV_Stanje;
			}
			set
			{
				if ((this._LDV_Stanje != value))
				{
					this.OnLDV_StanjeChanging(value);
					this.SendPropertyChanging();
					this._LDV_Stanje = value;
					this.SendPropertyChanged("LDV_Stanje");
					this.OnLDV_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_LayoutDvorana_LK_Event", Storage="_LK_Events", ThisKey="LDV_Id", OtherKey="EVE_LayoutId")]
		public EntitySet<LK_Event> LK_Events
		{
			get
			{
				return this._LK_Events;
			}
			set
			{
				this._LK_Events.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Dvorana_LK_LayoutDvorana", Storage="_LK_Dvorana", ThisKey="LDV_DvoranaId", OtherKey="DVO_Id", IsForeignKey=true)]
		public LK_Dvorana LK_Dvorana
		{
			get
			{
				return this._LK_Dvorana.Entity;
			}
			set
			{
				LK_Dvorana previousValue = this._LK_Dvorana.Entity;
				if (((previousValue != value) 
							|| (this._LK_Dvorana.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Dvorana.Entity = null;
						previousValue.LK_LayoutDvoranas.Remove(this);
					}
					this._LK_Dvorana.Entity = value;
					if ((value != null))
					{
						value.LK_LayoutDvoranas.Add(this);
						this._LDV_DvoranaId = value.DVO_Id;
					}
					else
					{
						this._LDV_DvoranaId = default(int);
					}
					this.SendPropertyChanged("LK_Dvorana");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_LayoutDvorana = this;
		}
		
		private void detach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_LayoutDvorana = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_Dvorana")]
	public partial class LK_Dvorana : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DVO_Id;
		
		private string _DVO_Naziv;
		
		private int _DVO_MjestoId;
		
		private System.Nullable<int> _DVO_KapacitetSjedenje;
		
		private System.Nullable<int> _DVO_KapacitetStajanje;
		
		private string _DVO_Adresa;
		
		private string _DVO_Telefon;
		
		private System.DateTime _DVO_Timestamp;
		
		private char _DVO_Stanje;
		
		private EntitySet<LK_Event> _LK_Events;
		
		private EntitySet<LK_LayoutDvorana> _LK_LayoutDvoranas;
		
		private EntityRef<LK_Mjesto> _LK_Mjesto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDVO_IdChanging(int value);
    partial void OnDVO_IdChanged();
    partial void OnDVO_NazivChanging(string value);
    partial void OnDVO_NazivChanged();
    partial void OnDVO_MjestoIdChanging(int value);
    partial void OnDVO_MjestoIdChanged();
    partial void OnDVO_KapacitetSjedenjeChanging(System.Nullable<int> value);
    partial void OnDVO_KapacitetSjedenjeChanged();
    partial void OnDVO_KapacitetStajanjeChanging(System.Nullable<int> value);
    partial void OnDVO_KapacitetStajanjeChanged();
    partial void OnDVO_AdresaChanging(string value);
    partial void OnDVO_AdresaChanged();
    partial void OnDVO_TelefonChanging(string value);
    partial void OnDVO_TelefonChanged();
    partial void OnDVO_TimestampChanging(System.DateTime value);
    partial void OnDVO_TimestampChanged();
    partial void OnDVO_StanjeChanging(char value);
    partial void OnDVO_StanjeChanged();
    #endregion
		
		public LK_Dvorana()
		{
			this._LK_Events = new EntitySet<LK_Event>(new Action<LK_Event>(this.attach_LK_Events), new Action<LK_Event>(this.detach_LK_Events));
			this._LK_LayoutDvoranas = new EntitySet<LK_LayoutDvorana>(new Action<LK_LayoutDvorana>(this.attach_LK_LayoutDvoranas), new Action<LK_LayoutDvorana>(this.detach_LK_LayoutDvoranas));
			this._LK_Mjesto = default(EntityRef<LK_Mjesto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DVO_Id
		{
			get
			{
				return this._DVO_Id;
			}
			set
			{
				if ((this._DVO_Id != value))
				{
					this.OnDVO_IdChanging(value);
					this.SendPropertyChanging();
					this._DVO_Id = value;
					this.SendPropertyChanged("DVO_Id");
					this.OnDVO_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DVO_Naziv
		{
			get
			{
				return this._DVO_Naziv;
			}
			set
			{
				if ((this._DVO_Naziv != value))
				{
					this.OnDVO_NazivChanging(value);
					this.SendPropertyChanging();
					this._DVO_Naziv = value;
					this.SendPropertyChanged("DVO_Naziv");
					this.OnDVO_NazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_MjestoId", DbType="Int NOT NULL")]
		public int DVO_MjestoId
		{
			get
			{
				return this._DVO_MjestoId;
			}
			set
			{
				if ((this._DVO_MjestoId != value))
				{
					if (this._LK_Mjesto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDVO_MjestoIdChanging(value);
					this.SendPropertyChanging();
					this._DVO_MjestoId = value;
					this.SendPropertyChanged("DVO_MjestoId");
					this.OnDVO_MjestoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_KapacitetSjedenje", DbType="Int")]
		public System.Nullable<int> DVO_KapacitetSjedenje
		{
			get
			{
				return this._DVO_KapacitetSjedenje;
			}
			set
			{
				if ((this._DVO_KapacitetSjedenje != value))
				{
					this.OnDVO_KapacitetSjedenjeChanging(value);
					this.SendPropertyChanging();
					this._DVO_KapacitetSjedenje = value;
					this.SendPropertyChanged("DVO_KapacitetSjedenje");
					this.OnDVO_KapacitetSjedenjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_KapacitetStajanje", DbType="Int")]
		public System.Nullable<int> DVO_KapacitetStajanje
		{
			get
			{
				return this._DVO_KapacitetStajanje;
			}
			set
			{
				if ((this._DVO_KapacitetStajanje != value))
				{
					this.OnDVO_KapacitetStajanjeChanging(value);
					this.SendPropertyChanging();
					this._DVO_KapacitetStajanje = value;
					this.SendPropertyChanged("DVO_KapacitetStajanje");
					this.OnDVO_KapacitetStajanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_Adresa", DbType="NVarChar(50)")]
		public string DVO_Adresa
		{
			get
			{
				return this._DVO_Adresa;
			}
			set
			{
				if ((this._DVO_Adresa != value))
				{
					this.OnDVO_AdresaChanging(value);
					this.SendPropertyChanging();
					this._DVO_Adresa = value;
					this.SendPropertyChanged("DVO_Adresa");
					this.OnDVO_AdresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_Telefon", DbType="NVarChar(25)")]
		public string DVO_Telefon
		{
			get
			{
				return this._DVO_Telefon;
			}
			set
			{
				if ((this._DVO_Telefon != value))
				{
					this.OnDVO_TelefonChanging(value);
					this.SendPropertyChanging();
					this._DVO_Telefon = value;
					this.SendPropertyChanged("DVO_Telefon");
					this.OnDVO_TelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime DVO_Timestamp
		{
			get
			{
				return this._DVO_Timestamp;
			}
			set
			{
				if ((this._DVO_Timestamp != value))
				{
					this.OnDVO_TimestampChanging(value);
					this.SendPropertyChanging();
					this._DVO_Timestamp = value;
					this.SendPropertyChanged("DVO_Timestamp");
					this.OnDVO_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVO_Stanje", DbType="Char(1) NOT NULL")]
		public char DVO_Stanje
		{
			get
			{
				return this._DVO_Stanje;
			}
			set
			{
				if ((this._DVO_Stanje != value))
				{
					this.OnDVO_StanjeChanging(value);
					this.SendPropertyChanging();
					this._DVO_Stanje = value;
					this.SendPropertyChanged("DVO_Stanje");
					this.OnDVO_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Dvorana_LK_Event", Storage="_LK_Events", ThisKey="DVO_Id", OtherKey="EVE_DvoranaId")]
		public EntitySet<LK_Event> LK_Events
		{
			get
			{
				return this._LK_Events;
			}
			set
			{
				this._LK_Events.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Dvorana_LK_LayoutDvorana", Storage="_LK_LayoutDvoranas", ThisKey="DVO_Id", OtherKey="LDV_DvoranaId")]
		public EntitySet<LK_LayoutDvorana> LK_LayoutDvoranas
		{
			get
			{
				return this._LK_LayoutDvoranas;
			}
			set
			{
				this._LK_LayoutDvoranas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Mjesto_LK_Dvorana", Storage="_LK_Mjesto", ThisKey="DVO_MjestoId", OtherKey="MJE_Id", IsForeignKey=true)]
		public LK_Mjesto LK_Mjesto
		{
			get
			{
				return this._LK_Mjesto.Entity;
			}
			set
			{
				LK_Mjesto previousValue = this._LK_Mjesto.Entity;
				if (((previousValue != value) 
							|| (this._LK_Mjesto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Mjesto.Entity = null;
						previousValue.LK_Dvoranas.Remove(this);
					}
					this._LK_Mjesto.Entity = value;
					if ((value != null))
					{
						value.LK_Dvoranas.Add(this);
						this._DVO_MjestoId = value.MJE_Id;
					}
					else
					{
						this._DVO_MjestoId = default(int);
					}
					this.SendPropertyChanged("LK_Mjesto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_Dvorana = this;
		}
		
		private void detach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_Dvorana = null;
		}
		
		private void attach_LK_LayoutDvoranas(LK_LayoutDvorana entity)
		{
			this.SendPropertyChanging();
			entity.LK_Dvorana = this;
		}
		
		private void detach_LK_LayoutDvoranas(LK_LayoutDvorana entity)
		{
			this.SendPropertyChanging();
			entity.LK_Dvorana = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_Mjesto")]
	public partial class LK_Mjesto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MJE_Id;
		
		private string _MJE_Naziv;
		
		private string _MJE_ZIP;
		
		private int _MJE_DrzavaId;
		
		private char _MJE_Stanje;
		
		private System.DateTime _MJE_Timestamp;
		
		private EntitySet<LK_Event> _LK_Events;
		
		private EntitySet<LK_Dvorana> _LK_Dvoranas;
		
		private EntityRef<LK_Drzava> _LK_Drzava;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMJE_IdChanging(int value);
    partial void OnMJE_IdChanged();
    partial void OnMJE_NazivChanging(string value);
    partial void OnMJE_NazivChanged();
    partial void OnMJE_ZIPChanging(string value);
    partial void OnMJE_ZIPChanged();
    partial void OnMJE_DrzavaIdChanging(int value);
    partial void OnMJE_DrzavaIdChanged();
    partial void OnMJE_StanjeChanging(char value);
    partial void OnMJE_StanjeChanged();
    partial void OnMJE_TimestampChanging(System.DateTime value);
    partial void OnMJE_TimestampChanged();
    #endregion
		
		public LK_Mjesto()
		{
			this._LK_Events = new EntitySet<LK_Event>(new Action<LK_Event>(this.attach_LK_Events), new Action<LK_Event>(this.detach_LK_Events));
			this._LK_Dvoranas = new EntitySet<LK_Dvorana>(new Action<LK_Dvorana>(this.attach_LK_Dvoranas), new Action<LK_Dvorana>(this.detach_LK_Dvoranas));
			this._LK_Drzava = default(EntityRef<LK_Drzava>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MJE_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MJE_Id
		{
			get
			{
				return this._MJE_Id;
			}
			set
			{
				if ((this._MJE_Id != value))
				{
					this.OnMJE_IdChanging(value);
					this.SendPropertyChanging();
					this._MJE_Id = value;
					this.SendPropertyChanged("MJE_Id");
					this.OnMJE_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MJE_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MJE_Naziv
		{
			get
			{
				return this._MJE_Naziv;
			}
			set
			{
				if ((this._MJE_Naziv != value))
				{
					this.OnMJE_NazivChanging(value);
					this.SendPropertyChanging();
					this._MJE_Naziv = value;
					this.SendPropertyChanged("MJE_Naziv");
					this.OnMJE_NazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MJE_ZIP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MJE_ZIP
		{
			get
			{
				return this._MJE_ZIP;
			}
			set
			{
				if ((this._MJE_ZIP != value))
				{
					this.OnMJE_ZIPChanging(value);
					this.SendPropertyChanging();
					this._MJE_ZIP = value;
					this.SendPropertyChanged("MJE_ZIP");
					this.OnMJE_ZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MJE_DrzavaId", DbType="Int NOT NULL")]
		public int MJE_DrzavaId
		{
			get
			{
				return this._MJE_DrzavaId;
			}
			set
			{
				if ((this._MJE_DrzavaId != value))
				{
					if (this._LK_Drzava.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMJE_DrzavaIdChanging(value);
					this.SendPropertyChanging();
					this._MJE_DrzavaId = value;
					this.SendPropertyChanged("MJE_DrzavaId");
					this.OnMJE_DrzavaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MJE_Stanje", DbType="Char(1) NOT NULL")]
		public char MJE_Stanje
		{
			get
			{
				return this._MJE_Stanje;
			}
			set
			{
				if ((this._MJE_Stanje != value))
				{
					this.OnMJE_StanjeChanging(value);
					this.SendPropertyChanging();
					this._MJE_Stanje = value;
					this.SendPropertyChanged("MJE_Stanje");
					this.OnMJE_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MJE_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime MJE_Timestamp
		{
			get
			{
				return this._MJE_Timestamp;
			}
			set
			{
				if ((this._MJE_Timestamp != value))
				{
					this.OnMJE_TimestampChanging(value);
					this.SendPropertyChanging();
					this._MJE_Timestamp = value;
					this.SendPropertyChanged("MJE_Timestamp");
					this.OnMJE_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Mjesto_LK_Event", Storage="_LK_Events", ThisKey="MJE_Id", OtherKey="EVE_MjestoId")]
		public EntitySet<LK_Event> LK_Events
		{
			get
			{
				return this._LK_Events;
			}
			set
			{
				this._LK_Events.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Mjesto_LK_Dvorana", Storage="_LK_Dvoranas", ThisKey="MJE_Id", OtherKey="DVO_MjestoId")]
		public EntitySet<LK_Dvorana> LK_Dvoranas
		{
			get
			{
				return this._LK_Dvoranas;
			}
			set
			{
				this._LK_Dvoranas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Drzava_LK_Mjesto", Storage="_LK_Drzava", ThisKey="MJE_DrzavaId", OtherKey="DRZ_Id", IsForeignKey=true)]
		public LK_Drzava LK_Drzava
		{
			get
			{
				return this._LK_Drzava.Entity;
			}
			set
			{
				LK_Drzava previousValue = this._LK_Drzava.Entity;
				if (((previousValue != value) 
							|| (this._LK_Drzava.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Drzava.Entity = null;
						previousValue.LK_Mjestos.Remove(this);
					}
					this._LK_Drzava.Entity = value;
					if ((value != null))
					{
						value.LK_Mjestos.Add(this);
						this._MJE_DrzavaId = value.DRZ_Id;
					}
					else
					{
						this._MJE_DrzavaId = default(int);
					}
					this.SendPropertyChanged("LK_Drzava");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_Mjesto = this;
		}
		
		private void detach_LK_Events(LK_Event entity)
		{
			this.SendPropertyChanging();
			entity.LK_Mjesto = null;
		}
		
		private void attach_LK_Dvoranas(LK_Dvorana entity)
		{
			this.SendPropertyChanging();
			entity.LK_Mjesto = this;
		}
		
		private void detach_LK_Dvoranas(LK_Dvorana entity)
		{
			this.SendPropertyChanging();
			entity.LK_Mjesto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_Drzava")]
	public partial class LK_Drzava : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DRZ_Id;
		
		private string _DRZ_Naziv;
		
		private System.DateTime _DRZ_Timestamp;
		
		private char _DRZ_Stanje;
		
		private EntitySet<LK_Mjesto> _LK_Mjestos;
		
		private EntityRef<LK_Drzava> _LK_Drzava2;
		
		private EntityRef<LK_Drzava> _LK_Drzava1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDRZ_IdChanging(int value);
    partial void OnDRZ_IdChanged();
    partial void OnDRZ_NazivChanging(string value);
    partial void OnDRZ_NazivChanged();
    partial void OnDRZ_TimestampChanging(System.DateTime value);
    partial void OnDRZ_TimestampChanged();
    partial void OnDRZ_StanjeChanging(char value);
    partial void OnDRZ_StanjeChanged();
    #endregion
		
		public LK_Drzava()
		{
			this._LK_Mjestos = new EntitySet<LK_Mjesto>(new Action<LK_Mjesto>(this.attach_LK_Mjestos), new Action<LK_Mjesto>(this.detach_LK_Mjestos));
			this._LK_Drzava2 = default(EntityRef<LK_Drzava>);
			this._LK_Drzava1 = default(EntityRef<LK_Drzava>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRZ_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DRZ_Id
		{
			get
			{
				return this._DRZ_Id;
			}
			set
			{
				if ((this._DRZ_Id != value))
				{
					if (this._LK_Drzava1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDRZ_IdChanging(value);
					this.SendPropertyChanging();
					this._DRZ_Id = value;
					this.SendPropertyChanged("DRZ_Id");
					this.OnDRZ_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRZ_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DRZ_Naziv
		{
			get
			{
				return this._DRZ_Naziv;
			}
			set
			{
				if ((this._DRZ_Naziv != value))
				{
					this.OnDRZ_NazivChanging(value);
					this.SendPropertyChanging();
					this._DRZ_Naziv = value;
					this.SendPropertyChanged("DRZ_Naziv");
					this.OnDRZ_NazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRZ_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime DRZ_Timestamp
		{
			get
			{
				return this._DRZ_Timestamp;
			}
			set
			{
				if ((this._DRZ_Timestamp != value))
				{
					this.OnDRZ_TimestampChanging(value);
					this.SendPropertyChanging();
					this._DRZ_Timestamp = value;
					this.SendPropertyChanged("DRZ_Timestamp");
					this.OnDRZ_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRZ_Stanje", DbType="Char(1) NOT NULL")]
		public char DRZ_Stanje
		{
			get
			{
				return this._DRZ_Stanje;
			}
			set
			{
				if ((this._DRZ_Stanje != value))
				{
					this.OnDRZ_StanjeChanging(value);
					this.SendPropertyChanging();
					this._DRZ_Stanje = value;
					this.SendPropertyChanged("DRZ_Stanje");
					this.OnDRZ_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Drzava_LK_Mjesto", Storage="_LK_Mjestos", ThisKey="DRZ_Id", OtherKey="MJE_DrzavaId")]
		public EntitySet<LK_Mjesto> LK_Mjestos
		{
			get
			{
				return this._LK_Mjestos;
			}
			set
			{
				this._LK_Mjestos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Drzava_LK_Drzava", Storage="_LK_Drzava2", ThisKey="DRZ_Id", OtherKey="DRZ_Id", IsUnique=true, IsForeignKey=false)]
		public LK_Drzava LK_Drzava2
		{
			get
			{
				return this._LK_Drzava2.Entity;
			}
			set
			{
				LK_Drzava previousValue = this._LK_Drzava2.Entity;
				if (((previousValue != value) 
							|| (this._LK_Drzava2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Drzava2.Entity = null;
						previousValue.LK_Drzava1 = null;
					}
					this._LK_Drzava2.Entity = value;
					if ((value != null))
					{
						value.LK_Drzava1 = this;
					}
					this.SendPropertyChanged("LK_Drzava2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LK_Drzava_LK_Drzava", Storage="_LK_Drzava1", ThisKey="DRZ_Id", OtherKey="DRZ_Id", IsForeignKey=true)]
		public LK_Drzava LK_Drzava1
		{
			get
			{
				return this._LK_Drzava1.Entity;
			}
			set
			{
				LK_Drzava previousValue = this._LK_Drzava1.Entity;
				if (((previousValue != value) 
							|| (this._LK_Drzava1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LK_Drzava1.Entity = null;
						previousValue.LK_Drzava2 = null;
					}
					this._LK_Drzava1.Entity = value;
					if ((value != null))
					{
						value.LK_Drzava2 = this;
						this._DRZ_Id = value.DRZ_Id;
					}
					else
					{
						this._DRZ_Id = default(int);
					}
					this.SendPropertyChanged("LK_Drzava1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LK_Mjestos(LK_Mjesto entity)
		{
			this.SendPropertyChanging();
			entity.LK_Drzava = this;
		}
		
		private void detach_LK_Mjestos(LK_Mjesto entity)
		{
			this.SendPropertyChanging();
			entity.LK_Drzava = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="prstacpr_prodaja.BK_ImageGalleries")]
	public partial class BK_ImageGallery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NazivGalerije;
		
		private EntitySet<BK_Image> _BK_Images;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivGalerijeChanging(string value);
    partial void OnNazivGalerijeChanged();
    #endregion
		
		public BK_ImageGallery()
		{
			this._BK_Images = new EntitySet<BK_Image>(new Action<BK_Image>(this.attach_BK_Images), new Action<BK_Image>(this.detach_BK_Images));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivGalerije", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NazivGalerije
		{
			get
			{
				return this._NazivGalerije;
			}
			set
			{
				if ((this._NazivGalerije != value))
				{
					this.OnNazivGalerijeChanging(value);
					this.SendPropertyChanging();
					this._NazivGalerije = value;
					this.SendPropertyChanged("NazivGalerije");
					this.OnNazivGalerijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BK_ImageGallery_BK_Image", Storage="_BK_Images", ThisKey="Id", OtherKey="GalleryId")]
		public EntitySet<BK_Image> BK_Images
		{
			get
			{
				return this._BK_Images;
			}
			set
			{
				this._BK_Images.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BK_Images(BK_Image entity)
		{
			this.SendPropertyChanging();
			entity.BK_ImageGallery = this;
		}
		
		private void detach_BK_Images(BK_Image entity)
		{
			this.SendPropertyChanging();
			entity.BK_ImageGallery = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="prstacpr_prodaja.BK_Images")]
	public partial class BK_Image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ImageName;
		
		private string _ImageAlt;
		
		private int _GalleryId;
		
		private EntityRef<BK_ImageGallery> _BK_ImageGallery;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnImageNameChanging(string value);
    partial void OnImageNameChanged();
    partial void OnImageAltChanging(string value);
    partial void OnImageAltChanged();
    partial void OnGalleryIdChanging(int value);
    partial void OnGalleryIdChanged();
    #endregion
		
		public BK_Image()
		{
			this._BK_ImageGallery = default(EntityRef<BK_ImageGallery>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this.OnImageNameChanging(value);
					this.SendPropertyChanging();
					this._ImageName = value;
					this.SendPropertyChanged("ImageName");
					this.OnImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageAlt", DbType="NVarChar(50)")]
		public string ImageAlt
		{
			get
			{
				return this._ImageAlt;
			}
			set
			{
				if ((this._ImageAlt != value))
				{
					this.OnImageAltChanging(value);
					this.SendPropertyChanging();
					this._ImageAlt = value;
					this.SendPropertyChanged("ImageAlt");
					this.OnImageAltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GalleryId", DbType="Int NOT NULL")]
		public int GalleryId
		{
			get
			{
				return this._GalleryId;
			}
			set
			{
				if ((this._GalleryId != value))
				{
					if (this._BK_ImageGallery.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGalleryIdChanging(value);
					this.SendPropertyChanging();
					this._GalleryId = value;
					this.SendPropertyChanged("GalleryId");
					this.OnGalleryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BK_ImageGallery_BK_Image", Storage="_BK_ImageGallery", ThisKey="GalleryId", OtherKey="Id", IsForeignKey=true)]
		public BK_ImageGallery BK_ImageGallery
		{
			get
			{
				return this._BK_ImageGallery.Entity;
			}
			set
			{
				BK_ImageGallery previousValue = this._BK_ImageGallery.Entity;
				if (((previousValue != value) 
							|| (this._BK_ImageGallery.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BK_ImageGallery.Entity = null;
						previousValue.BK_Images.Remove(this);
					}
					this._BK_ImageGallery.Entity = value;
					if ((value != null))
					{
						value.BK_Images.Add(this);
						this._GalleryId = value.Id;
					}
					else
					{
						this._GalleryId = default(int);
					}
					this.SendPropertyChanged("BK_ImageGallery");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="prstacpr_prodaja.BK_REL_Event_ImageGalleries")]
	public partial class BK_REL_Event_ImageGallery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _EventId;
		
		private int _ImageGalleriesId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEventIdChanging(int value);
    partial void OnEventIdChanged();
    partial void OnImageGalleriesIdChanging(int value);
    partial void OnImageGalleriesIdChanged();
    #endregion
		
		public BK_REL_Event_ImageGallery()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventId", DbType="Int NOT NULL")]
		public int EventId
		{
			get
			{
				return this._EventId;
			}
			set
			{
				if ((this._EventId != value))
				{
					this.OnEventIdChanging(value);
					this.SendPropertyChanging();
					this._EventId = value;
					this.SendPropertyChanged("EventId");
					this.OnEventIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageGalleriesId", DbType="Int NOT NULL")]
		public int ImageGalleriesId
		{
			get
			{
				return this._ImageGalleriesId;
			}
			set
			{
				if ((this._ImageGalleriesId != value))
				{
					this.OnImageGalleriesIdChanging(value);
					this.SendPropertyChanging();
					this._ImageGalleriesId = value;
					this.SendPropertyChanged("ImageGalleriesId");
					this.OnImageGalleriesIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
