<?xml version="1.0" encoding="utf-8"?><Database Name="prstacpr_bk_testna" Class="AdriaTicketDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql4.mojsite.com,1555;Initial Catalog=prstacpr_bk_testna;User ID=prstacpr_prodaja" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="prstacpr_bk_testnaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SEC_LK_Korisnik" Member="SEC_LK_Korisniks">
    <Type Name="SEC_LK_Korisnik">
      <Column Name="KOR_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KOR_IdDjelatnik" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KOR_Login" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="KOR_Zaporka" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="KOR_Napomena" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_Event" Member="LK_Events">
    <Type Name="LK_Event">
      <Column Name="EVE_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EVE_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EVE_Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVE_Opis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_MjestoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_DvoranaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_LayoutId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_StatusEventaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EVE_PotrebanKupac" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EVE_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EVE_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="EVE_DatumOdPretprodaja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVE_DatumOdProdaja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVE_PostotakProvizije" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="EVE_OrganizatorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EVE_PrikaziNaWebu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_ImagePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ImageSmallPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ImageExist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_Napomena" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ReklamaPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ReklamaExist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_BrojGlavnogEventa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_FlagOnlineProdaja" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_MaksimalniBrojKarata" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_PDVIznos" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Association Name="LK_Event_BK_VideoGallery" Member="BK_VideoGalleries" ThisKey="EVE_Id" OtherKey="eventID" Type="BK_VideoGallery" />
      <Association Name="LK_Event_LK_Cijena" Member="LK_Cijenas" ThisKey="EVE_Id" OtherKey="CIJ_EventId" Type="LK_Cijena" />
      <Association Name="LK_StatusEventa_LK_Event" Member="LK_StatusEventa" ThisKey="EVE_StatusEventaId" OtherKey="SEV_Id" Type="LK_StatusEventa" IsForeignKey="true" />
      <Association Name="LK_Organizator_LK_Event" Member="LK_Organizator" ThisKey="EVE_OrganizatorId" OtherKey="ORG_Id" Type="LK_Organizator" IsForeignKey="true" />
      <Association Name="LK_LayoutDvorana_LK_Event" Member="LK_LayoutDvorana" ThisKey="EVE_LayoutId" OtherKey="LDV_Id" Type="LK_LayoutDvorana" IsForeignKey="true" />
      <Association Name="LK_Dvorana_LK_Event" Member="LK_Dvorana" ThisKey="EVE_DvoranaId" OtherKey="DVO_Id" Type="LK_Dvorana" IsForeignKey="true" />
      <Association Name="LK_Mjesto_LK_Event" Member="LK_Mjesto" ThisKey="EVE_MjestoId" OtherKey="MJE_Id" Type="LK_Mjesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_StatusEventa" Member="LK_StatusEventas">
    <Type Name="LK_StatusEventa">
      <Column Name="SEV_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SEV_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SEV_SkraceniNaziv" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="SEV_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SEV_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="LK_StatusEventa_LK_Event" Member="LK_Events" ThisKey="SEV_Id" OtherKey="EVE_StatusEventaId" Type="LK_Event" />
    </Type>
  </Table>
  <Table Name="dbo.REL_EventLayoutSektor" Member="REL_EventLayoutSektors">
    <Type Name="REL_EventLayoutSektor">
      <Column Name="ELS_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ELS_EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ELS_LayoutDvoranaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ELS_SektorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ELS_DopustiStorniranje" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ELS_Ulaz" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ELS_KapacitetSektora" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ELS_GrupaSektoraId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ELS_Rezervirano" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_Organizator" Member="LK_Organizators">
    <Type Name="LK_Organizator">
      <Column Name="ORG_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ORG_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ORG_Adresa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ORG_OIB" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ORG_FlagPDV" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ORG_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ORG_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="LK_Organizator_LK_Event" Member="LK_Events" ThisKey="ORG_Id" OtherKey="EVE_OrganizatorId" Type="LK_Event" />
    </Type>
  </Table>
  <Table Name="dbo.LK_LayoutDvorana" Member="LK_LayoutDvoranas">
    <Type Name="LK_LayoutDvorana">
      <Column Name="LDV_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LDV_Opis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LDV_DvoranaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LDV_KapacitetSjedenje" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LDV_KapacitetStajanje" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LDV_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LDV_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="LK_LayoutDvorana_LK_Event" Member="LK_Events" ThisKey="LDV_Id" OtherKey="EVE_LayoutId" Type="LK_Event" />
      <Association Name="LK_Dvorana_LK_LayoutDvorana" Member="LK_Dvorana" ThisKey="LDV_DvoranaId" OtherKey="DVO_Id" Type="LK_Dvorana" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_Dvorana" Member="LK_Dvoranas">
    <Type Name="LK_Dvorana">
      <Column Name="DVO_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DVO_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DVO_MjestoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DVO_KapacitetSjedenje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DVO_KapacitetStajanje" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DVO_Adresa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DVO_Telefon" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="DVO_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DVO_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="LK_Dvorana_LK_Event" Member="LK_Events" ThisKey="DVO_Id" OtherKey="EVE_DvoranaId" Type="LK_Event" />
      <Association Name="LK_Dvorana_LK_LayoutDvorana" Member="LK_LayoutDvoranas" ThisKey="DVO_Id" OtherKey="LDV_DvoranaId" Type="LK_LayoutDvorana" />
      <Association Name="LK_Mjesto_LK_Dvorana" Member="LK_Mjesto" ThisKey="DVO_MjestoId" OtherKey="MJE_Id" Type="LK_Mjesto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_Mjesto" Member="LK_Mjestos">
    <Type Name="LK_Mjesto">
      <Column Name="MJE_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MJE_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MJE_ZIP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MJE_DrzavaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MJE_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="MJE_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LK_Mjesto_LK_Event" Member="LK_Events" ThisKey="MJE_Id" OtherKey="EVE_MjestoId" Type="LK_Event" />
      <Association Name="LK_Mjesto_LK_Dvorana" Member="LK_Dvoranas" ThisKey="MJE_Id" OtherKey="DVO_MjestoId" Type="LK_Dvorana" />
      <Association Name="LK_Mjesto_BK_TownsForWeb" Member="BK_TownsForWebs" ThisKey="MJE_Id" OtherKey="TownId" Type="BK_TownsForWeb" />
      <Association Name="LK_Drzava_LK_Mjesto" Member="LK_Drzava" ThisKey="MJE_DrzavaId" OtherKey="DRZ_Id" Type="LK_Drzava" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_Drzava" Member="LK_Drzavas">
    <Type Name="LK_Drzava">
      <Column Name="DRZ_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DRZ_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DRZ_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DRZ_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="LK_Drzava_LK_Mjesto" Member="LK_Mjestos" ThisKey="DRZ_Id" OtherKey="MJE_DrzavaId" Type="LK_Mjesto" />
      <Association Name="LK_Drzava_LK_Drzava" Member="LK_Drzava2" ThisKey="DRZ_Id" OtherKey="DRZ_Id" Type="LK_Drzava" Cardinality="One" />
      <Association Name="LK_Drzava_LK_Drzava" Member="LK_Drzava1" ThisKey="DRZ_Id" OtherKey="DRZ_Id" Type="LK_Drzava" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="prstacpr_prodaja.BK_ImageGalleries" Member="BK_ImageGalleries">
    <Type Name="BK_ImageGallery">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NazivGalerije" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BK_ImageGallery_BK_Image" Member="BK_Images" ThisKey="Id" OtherKey="GalleryId" Type="BK_Image" />
    </Type>
  </Table>
  <Table Name="prstacpr_prodaja.BK_Images" Member="BK_Images">
    <Type Name="BK_Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ImageAlt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GalleryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BK_ImageGallery_BK_Image" Member="BK_ImageGallery" ThisKey="GalleryId" OtherKey="Id" Type="BK_ImageGallery" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="prstacpr_prodaja.BK_REL_Event_ImageGalleries" Member="BK_REL_Event_ImageGalleries">
    <Type Name="BK_REL_Event_ImageGallery">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageGalleriesId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="prstacpr_prodaja.BK_VideoGallery" Member="BK_VideoGalleries">
    <Type Name="BK_VideoGallery">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="videoLink" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="eventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LK_Event_BK_VideoGallery" Member="LK_Event" ThisKey="eventID" OtherKey="EVE_Id" Type="LK_Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_Cijena" Member="LK_Cijenas">
    <Type Name="LK_Cijena">
      <Column Name="CIJ_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CIJ_SektorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CIJ_EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CIJ_IznosPretprodaja" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="CIJ_IznosProdaja" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="CIJ_IznosNaDan" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="CIJ_IznosPopusta" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Association Name="LK_Event_LK_Cijena" Member="LK_Event" ThisKey="CIJ_EventId" OtherKey="EVE_Id" Type="LK_Event" IsForeignKey="true" />
      <Association Name="LK_Sektor_LK_Cijena" Member="LK_Sektor" ThisKey="CIJ_SektorId" OtherKey="SEK_Id" Type="LK_Sektor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LK_Sektor" Member="LK_Sektors">
    <Type Name="LK_Sektor">
      <Column Name="SEK_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SEK_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SEK_DvoranaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SEK_FlagSjedenje" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SEK_Kapacitet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SEK_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SEK_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="SEK_NazivTop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEK_NazivLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LK_Sektor_LK_Cijena" Member="LK_Cijenas" ThisKey="SEK_Id" OtherKey="CIJ_SektorId" Type="LK_Cijena" />
    </Type>
  </Table>
  <Table Name="dbo.LK_ProdajnoMjestoWeb" Member="LK_ProdajnoMjestoWebs">
    <Type Name="LK_ProdajnoMjestoWeb">
      <Column Name="PMW_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PMW_Grad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PMW_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PMW_Adresa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PMW_Telefon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BK_Lng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BK_Lat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="prstacpr_prodaja.BK_TownsForWeb" Member="BK_TownsForWebs">
    <Type Name="BK_TownsForWeb">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TownId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LK_Mjesto_BK_TownsForWeb" Member="LK_Mjesto" ThisKey="TownId" OtherKey="MJE_Id" Type="LK_Mjesto" IsForeignKey="true" />
    </Type>
  </Table>
</Database>