#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdriaTicket.com.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="prstacpr_bk_testna")]
	public partial class AdriaTicketDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSEC_LK_Korisnik(SEC_LK_Korisnik instance);
    partial void UpdateSEC_LK_Korisnik(SEC_LK_Korisnik instance);
    partial void DeleteSEC_LK_Korisnik(SEC_LK_Korisnik instance);
    partial void InsertLK_Event(LK_Event instance);
    partial void UpdateLK_Event(LK_Event instance);
    partial void DeleteLK_Event(LK_Event instance);
    #endregion
		
		public AdriaTicketDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["prstacpr_bk_testnaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaTicketDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SEC_LK_Korisnik> SEC_LK_Korisniks
		{
			get
			{
				return this.GetTable<SEC_LK_Korisnik>();
			}
		}
		
		public System.Data.Linq.Table<LK_Event> LK_Events
		{
			get
			{
				return this.GetTable<LK_Event>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SEC_LK_Korisnik")]
	public partial class SEC_LK_Korisnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KOR_Id;
		
		private int _KOR_IdDjelatnik;
		
		private string _KOR_Login;
		
		private string _KOR_Zaporka;
		
		private string _KOR_Napomena;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKOR_IdChanging(int value);
    partial void OnKOR_IdChanged();
    partial void OnKOR_IdDjelatnikChanging(int value);
    partial void OnKOR_IdDjelatnikChanged();
    partial void OnKOR_LoginChanging(string value);
    partial void OnKOR_LoginChanged();
    partial void OnKOR_ZaporkaChanging(string value);
    partial void OnKOR_ZaporkaChanged();
    partial void OnKOR_NapomenaChanging(string value);
    partial void OnKOR_NapomenaChanged();
    #endregion
		
		public SEC_LK_Korisnik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KOR_Id
		{
			get
			{
				return this._KOR_Id;
			}
			set
			{
				if ((this._KOR_Id != value))
				{
					this.OnKOR_IdChanging(value);
					this.SendPropertyChanging();
					this._KOR_Id = value;
					this.SendPropertyChanged("KOR_Id");
					this.OnKOR_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_IdDjelatnik", DbType="Int NOT NULL")]
		public int KOR_IdDjelatnik
		{
			get
			{
				return this._KOR_IdDjelatnik;
			}
			set
			{
				if ((this._KOR_IdDjelatnik != value))
				{
					this.OnKOR_IdDjelatnikChanging(value);
					this.SendPropertyChanging();
					this._KOR_IdDjelatnik = value;
					this.SendPropertyChanged("KOR_IdDjelatnik");
					this.OnKOR_IdDjelatnikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Login", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string KOR_Login
		{
			get
			{
				return this._KOR_Login;
			}
			set
			{
				if ((this._KOR_Login != value))
				{
					this.OnKOR_LoginChanging(value);
					this.SendPropertyChanging();
					this._KOR_Login = value;
					this.SendPropertyChanged("KOR_Login");
					this.OnKOR_LoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Zaporka", DbType="VarChar(MAX)")]
		public string KOR_Zaporka
		{
			get
			{
				return this._KOR_Zaporka;
			}
			set
			{
				if ((this._KOR_Zaporka != value))
				{
					this.OnKOR_ZaporkaChanging(value);
					this.SendPropertyChanging();
					this._KOR_Zaporka = value;
					this.SendPropertyChanged("KOR_Zaporka");
					this.OnKOR_ZaporkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KOR_Napomena", DbType="NVarChar(100)")]
		public string KOR_Napomena
		{
			get
			{
				return this._KOR_Napomena;
			}
			set
			{
				if ((this._KOR_Napomena != value))
				{
					this.OnKOR_NapomenaChanging(value);
					this.SendPropertyChanging();
					this._KOR_Napomena = value;
					this.SendPropertyChanged("KOR_Napomena");
					this.OnKOR_NapomenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LK_Event")]
	public partial class LK_Event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EVE_Id;
		
		private string _EVE_Naziv;
		
		private System.Nullable<System.DateTime> _EVE_Datum;
		
		private string _EVE_Opis;
		
		private System.Nullable<int> _EVE_MjestoId;
		
		private System.Nullable<int> _EVE_DvoranaId;
		
		private System.Nullable<int> _EVE_LayoutId;
		
		private int _EVE_StatusEventaId;
		
		private System.Nullable<bool> _EVE_PotrebanKupac;
		
		private System.DateTime _EVE_Timestamp;
		
		private char _EVE_Stanje;
		
		private System.Nullable<System.DateTime> _EVE_DatumOdPretprodaja;
		
		private System.Nullable<System.DateTime> _EVE_DatumOdProdaja;
		
		private decimal _EVE_PostotakProvizije;
		
		private int _EVE_OrganizatorId;
		
		private bool _EVE_PrikaziNaWebu;
		
		private string _EVE_ImagePath;
		
		private string _EVE_ImageSmallPath;
		
		private bool _EVE_ImageExist;
		
		private string _EVE_Napomena;
		
		private string _EVE_ReklamaPath;
		
		private bool _EVE_ReklamaExist;
		
		private System.Nullable<int> _EVE_BrojGlavnogEventa;
		
		private bool _EVE_FlagOnlineProdaja;
		
		private System.Nullable<int> _EVE_MaksimalniBrojKarata;
		
		private System.Nullable<decimal> _EVE_PDVIznos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEVE_IdChanging(int value);
    partial void OnEVE_IdChanged();
    partial void OnEVE_NazivChanging(string value);
    partial void OnEVE_NazivChanged();
    partial void OnEVE_DatumChanging(System.Nullable<System.DateTime> value);
    partial void OnEVE_DatumChanged();
    partial void OnEVE_OpisChanging(string value);
    partial void OnEVE_OpisChanged();
    partial void OnEVE_MjestoIdChanging(System.Nullable<int> value);
    partial void OnEVE_MjestoIdChanged();
    partial void OnEVE_DvoranaIdChanging(System.Nullable<int> value);
    partial void OnEVE_DvoranaIdChanged();
    partial void OnEVE_LayoutIdChanging(System.Nullable<int> value);
    partial void OnEVE_LayoutIdChanged();
    partial void OnEVE_StatusEventaIdChanging(int value);
    partial void OnEVE_StatusEventaIdChanged();
    partial void OnEVE_PotrebanKupacChanging(System.Nullable<bool> value);
    partial void OnEVE_PotrebanKupacChanged();
    partial void OnEVE_TimestampChanging(System.DateTime value);
    partial void OnEVE_TimestampChanged();
    partial void OnEVE_StanjeChanging(char value);
    partial void OnEVE_StanjeChanged();
    partial void OnEVE_DatumOdPretprodajaChanging(System.Nullable<System.DateTime> value);
    partial void OnEVE_DatumOdPretprodajaChanged();
    partial void OnEVE_DatumOdProdajaChanging(System.Nullable<System.DateTime> value);
    partial void OnEVE_DatumOdProdajaChanged();
    partial void OnEVE_PostotakProvizijeChanging(decimal value);
    partial void OnEVE_PostotakProvizijeChanged();
    partial void OnEVE_OrganizatorIdChanging(int value);
    partial void OnEVE_OrganizatorIdChanged();
    partial void OnEVE_PrikaziNaWebuChanging(bool value);
    partial void OnEVE_PrikaziNaWebuChanged();
    partial void OnEVE_ImagePathChanging(string value);
    partial void OnEVE_ImagePathChanged();
    partial void OnEVE_ImageSmallPathChanging(string value);
    partial void OnEVE_ImageSmallPathChanged();
    partial void OnEVE_ImageExistChanging(bool value);
    partial void OnEVE_ImageExistChanged();
    partial void OnEVE_NapomenaChanging(string value);
    partial void OnEVE_NapomenaChanged();
    partial void OnEVE_ReklamaPathChanging(string value);
    partial void OnEVE_ReklamaPathChanged();
    partial void OnEVE_ReklamaExistChanging(bool value);
    partial void OnEVE_ReklamaExistChanged();
    partial void OnEVE_BrojGlavnogEventaChanging(System.Nullable<int> value);
    partial void OnEVE_BrojGlavnogEventaChanged();
    partial void OnEVE_FlagOnlineProdajaChanging(bool value);
    partial void OnEVE_FlagOnlineProdajaChanged();
    partial void OnEVE_MaksimalniBrojKarataChanging(System.Nullable<int> value);
    partial void OnEVE_MaksimalniBrojKarataChanged();
    partial void OnEVE_PDVIznosChanging(System.Nullable<decimal> value);
    partial void OnEVE_PDVIznosChanged();
    #endregion
		
		public LK_Event()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EVE_Id
		{
			get
			{
				return this._EVE_Id;
			}
			set
			{
				if ((this._EVE_Id != value))
				{
					this.OnEVE_IdChanging(value);
					this.SendPropertyChanging();
					this._EVE_Id = value;
					this.SendPropertyChanged("EVE_Id");
					this.OnEVE_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Naziv", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EVE_Naziv
		{
			get
			{
				return this._EVE_Naziv;
			}
			set
			{
				if ((this._EVE_Naziv != value))
				{
					this.OnEVE_NazivChanging(value);
					this.SendPropertyChanging();
					this._EVE_Naziv = value;
					this.SendPropertyChanged("EVE_Naziv");
					this.OnEVE_NazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Datum", DbType="DateTime")]
		public System.Nullable<System.DateTime> EVE_Datum
		{
			get
			{
				return this._EVE_Datum;
			}
			set
			{
				if ((this._EVE_Datum != value))
				{
					this.OnEVE_DatumChanging(value);
					this.SendPropertyChanging();
					this._EVE_Datum = value;
					this.SendPropertyChanged("EVE_Datum");
					this.OnEVE_DatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Opis", DbType="NVarChar(MAX)")]
		public string EVE_Opis
		{
			get
			{
				return this._EVE_Opis;
			}
			set
			{
				if ((this._EVE_Opis != value))
				{
					this.OnEVE_OpisChanging(value);
					this.SendPropertyChanging();
					this._EVE_Opis = value;
					this.SendPropertyChanged("EVE_Opis");
					this.OnEVE_OpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_MjestoId", DbType="Int")]
		public System.Nullable<int> EVE_MjestoId
		{
			get
			{
				return this._EVE_MjestoId;
			}
			set
			{
				if ((this._EVE_MjestoId != value))
				{
					this.OnEVE_MjestoIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_MjestoId = value;
					this.SendPropertyChanged("EVE_MjestoId");
					this.OnEVE_MjestoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_DvoranaId", DbType="Int")]
		public System.Nullable<int> EVE_DvoranaId
		{
			get
			{
				return this._EVE_DvoranaId;
			}
			set
			{
				if ((this._EVE_DvoranaId != value))
				{
					this.OnEVE_DvoranaIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_DvoranaId = value;
					this.SendPropertyChanged("EVE_DvoranaId");
					this.OnEVE_DvoranaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_LayoutId", DbType="Int")]
		public System.Nullable<int> EVE_LayoutId
		{
			get
			{
				return this._EVE_LayoutId;
			}
			set
			{
				if ((this._EVE_LayoutId != value))
				{
					this.OnEVE_LayoutIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_LayoutId = value;
					this.SendPropertyChanged("EVE_LayoutId");
					this.OnEVE_LayoutIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_StatusEventaId", DbType="Int NOT NULL")]
		public int EVE_StatusEventaId
		{
			get
			{
				return this._EVE_StatusEventaId;
			}
			set
			{
				if ((this._EVE_StatusEventaId != value))
				{
					this.OnEVE_StatusEventaIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_StatusEventaId = value;
					this.SendPropertyChanged("EVE_StatusEventaId");
					this.OnEVE_StatusEventaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PotrebanKupac", DbType="Bit")]
		public System.Nullable<bool> EVE_PotrebanKupac
		{
			get
			{
				return this._EVE_PotrebanKupac;
			}
			set
			{
				if ((this._EVE_PotrebanKupac != value))
				{
					this.OnEVE_PotrebanKupacChanging(value);
					this.SendPropertyChanging();
					this._EVE_PotrebanKupac = value;
					this.SendPropertyChanged("EVE_PotrebanKupac");
					this.OnEVE_PotrebanKupacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Timestamp", DbType="DateTime NOT NULL")]
		public System.DateTime EVE_Timestamp
		{
			get
			{
				return this._EVE_Timestamp;
			}
			set
			{
				if ((this._EVE_Timestamp != value))
				{
					this.OnEVE_TimestampChanging(value);
					this.SendPropertyChanging();
					this._EVE_Timestamp = value;
					this.SendPropertyChanged("EVE_Timestamp");
					this.OnEVE_TimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Stanje", DbType="Char(1) NOT NULL")]
		public char EVE_Stanje
		{
			get
			{
				return this._EVE_Stanje;
			}
			set
			{
				if ((this._EVE_Stanje != value))
				{
					this.OnEVE_StanjeChanging(value);
					this.SendPropertyChanging();
					this._EVE_Stanje = value;
					this.SendPropertyChanged("EVE_Stanje");
					this.OnEVE_StanjeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_DatumOdPretprodaja", DbType="DateTime")]
		public System.Nullable<System.DateTime> EVE_DatumOdPretprodaja
		{
			get
			{
				return this._EVE_DatumOdPretprodaja;
			}
			set
			{
				if ((this._EVE_DatumOdPretprodaja != value))
				{
					this.OnEVE_DatumOdPretprodajaChanging(value);
					this.SendPropertyChanging();
					this._EVE_DatumOdPretprodaja = value;
					this.SendPropertyChanged("EVE_DatumOdPretprodaja");
					this.OnEVE_DatumOdPretprodajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_DatumOdProdaja", DbType="DateTime")]
		public System.Nullable<System.DateTime> EVE_DatumOdProdaja
		{
			get
			{
				return this._EVE_DatumOdProdaja;
			}
			set
			{
				if ((this._EVE_DatumOdProdaja != value))
				{
					this.OnEVE_DatumOdProdajaChanging(value);
					this.SendPropertyChanging();
					this._EVE_DatumOdProdaja = value;
					this.SendPropertyChanged("EVE_DatumOdProdaja");
					this.OnEVE_DatumOdProdajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PostotakProvizije", DbType="Decimal(9,2) NOT NULL")]
		public decimal EVE_PostotakProvizije
		{
			get
			{
				return this._EVE_PostotakProvizije;
			}
			set
			{
				if ((this._EVE_PostotakProvizije != value))
				{
					this.OnEVE_PostotakProvizijeChanging(value);
					this.SendPropertyChanging();
					this._EVE_PostotakProvizije = value;
					this.SendPropertyChanged("EVE_PostotakProvizije");
					this.OnEVE_PostotakProvizijeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_OrganizatorId", DbType="Int NOT NULL")]
		public int EVE_OrganizatorId
		{
			get
			{
				return this._EVE_OrganizatorId;
			}
			set
			{
				if ((this._EVE_OrganizatorId != value))
				{
					this.OnEVE_OrganizatorIdChanging(value);
					this.SendPropertyChanging();
					this._EVE_OrganizatorId = value;
					this.SendPropertyChanged("EVE_OrganizatorId");
					this.OnEVE_OrganizatorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PrikaziNaWebu", DbType="Bit NOT NULL")]
		public bool EVE_PrikaziNaWebu
		{
			get
			{
				return this._EVE_PrikaziNaWebu;
			}
			set
			{
				if ((this._EVE_PrikaziNaWebu != value))
				{
					this.OnEVE_PrikaziNaWebuChanging(value);
					this.SendPropertyChanging();
					this._EVE_PrikaziNaWebu = value;
					this.SendPropertyChanged("EVE_PrikaziNaWebu");
					this.OnEVE_PrikaziNaWebuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ImagePath", DbType="NVarChar(MAX)")]
		public string EVE_ImagePath
		{
			get
			{
				return this._EVE_ImagePath;
			}
			set
			{
				if ((this._EVE_ImagePath != value))
				{
					this.OnEVE_ImagePathChanging(value);
					this.SendPropertyChanging();
					this._EVE_ImagePath = value;
					this.SendPropertyChanged("EVE_ImagePath");
					this.OnEVE_ImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ImageSmallPath", DbType="NVarChar(MAX)")]
		public string EVE_ImageSmallPath
		{
			get
			{
				return this._EVE_ImageSmallPath;
			}
			set
			{
				if ((this._EVE_ImageSmallPath != value))
				{
					this.OnEVE_ImageSmallPathChanging(value);
					this.SendPropertyChanging();
					this._EVE_ImageSmallPath = value;
					this.SendPropertyChanged("EVE_ImageSmallPath");
					this.OnEVE_ImageSmallPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ImageExist", DbType="Bit NOT NULL")]
		public bool EVE_ImageExist
		{
			get
			{
				return this._EVE_ImageExist;
			}
			set
			{
				if ((this._EVE_ImageExist != value))
				{
					this.OnEVE_ImageExistChanging(value);
					this.SendPropertyChanging();
					this._EVE_ImageExist = value;
					this.SendPropertyChanged("EVE_ImageExist");
					this.OnEVE_ImageExistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_Napomena", DbType="NVarChar(MAX)")]
		public string EVE_Napomena
		{
			get
			{
				return this._EVE_Napomena;
			}
			set
			{
				if ((this._EVE_Napomena != value))
				{
					this.OnEVE_NapomenaChanging(value);
					this.SendPropertyChanging();
					this._EVE_Napomena = value;
					this.SendPropertyChanged("EVE_Napomena");
					this.OnEVE_NapomenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ReklamaPath", DbType="NVarChar(MAX)")]
		public string EVE_ReklamaPath
		{
			get
			{
				return this._EVE_ReklamaPath;
			}
			set
			{
				if ((this._EVE_ReklamaPath != value))
				{
					this.OnEVE_ReklamaPathChanging(value);
					this.SendPropertyChanging();
					this._EVE_ReklamaPath = value;
					this.SendPropertyChanged("EVE_ReklamaPath");
					this.OnEVE_ReklamaPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_ReklamaExist", DbType="Bit NOT NULL")]
		public bool EVE_ReklamaExist
		{
			get
			{
				return this._EVE_ReklamaExist;
			}
			set
			{
				if ((this._EVE_ReklamaExist != value))
				{
					this.OnEVE_ReklamaExistChanging(value);
					this.SendPropertyChanging();
					this._EVE_ReklamaExist = value;
					this.SendPropertyChanged("EVE_ReklamaExist");
					this.OnEVE_ReklamaExistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_BrojGlavnogEventa", DbType="Int")]
		public System.Nullable<int> EVE_BrojGlavnogEventa
		{
			get
			{
				return this._EVE_BrojGlavnogEventa;
			}
			set
			{
				if ((this._EVE_BrojGlavnogEventa != value))
				{
					this.OnEVE_BrojGlavnogEventaChanging(value);
					this.SendPropertyChanging();
					this._EVE_BrojGlavnogEventa = value;
					this.SendPropertyChanged("EVE_BrojGlavnogEventa");
					this.OnEVE_BrojGlavnogEventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_FlagOnlineProdaja", DbType="Bit NOT NULL")]
		public bool EVE_FlagOnlineProdaja
		{
			get
			{
				return this._EVE_FlagOnlineProdaja;
			}
			set
			{
				if ((this._EVE_FlagOnlineProdaja != value))
				{
					this.OnEVE_FlagOnlineProdajaChanging(value);
					this.SendPropertyChanging();
					this._EVE_FlagOnlineProdaja = value;
					this.SendPropertyChanged("EVE_FlagOnlineProdaja");
					this.OnEVE_FlagOnlineProdajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_MaksimalniBrojKarata", DbType="Int")]
		public System.Nullable<int> EVE_MaksimalniBrojKarata
		{
			get
			{
				return this._EVE_MaksimalniBrojKarata;
			}
			set
			{
				if ((this._EVE_MaksimalniBrojKarata != value))
				{
					this.OnEVE_MaksimalniBrojKarataChanging(value);
					this.SendPropertyChanging();
					this._EVE_MaksimalniBrojKarata = value;
					this.SendPropertyChanged("EVE_MaksimalniBrojKarata");
					this.OnEVE_MaksimalniBrojKarataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVE_PDVIznos", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> EVE_PDVIznos
		{
			get
			{
				return this._EVE_PDVIznos;
			}
			set
			{
				if ((this._EVE_PDVIznos != value))
				{
					this.OnEVE_PDVIznosChanging(value);
					this.SendPropertyChanging();
					this._EVE_PDVIznos = value;
					this.SendPropertyChanged("EVE_PDVIznos");
					this.OnEVE_PDVIznosChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
