<?xml version="1.0" encoding="utf-8"?><Database Name="prstacpr_bk_testna" Class="EventDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql4.mojsite.com,1555;Initial Catalog=prstacpr_bk_testna;User ID=prstacpr_prodaja" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="prstacpr_bk_testnaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LK_Event" Member="LK_Events">
    <Type Name="LK_Event">
      <Column Name="EVE_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EVE_Naziv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EVE_Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVE_Opis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_MjestoId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_DvoranaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_LayoutId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_StatusEventaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EVE_PotrebanKupac" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EVE_Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EVE_Stanje" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="EVE_DatumOdPretprodaja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVE_DatumOdProdaja" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EVE_PostotakProvizije" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="EVE_OrganizatorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EVE_PrikaziNaWebu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_ImagePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ImageSmallPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ImageExist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_Napomena" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ReklamaPath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EVE_ReklamaExist" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_BrojGlavnogEventa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_FlagOnlineProdaja" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EVE_MaksimalniBrojKarata" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EVE_PDVIznos" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>